// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auto_stop_snapshots.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActivitySnapshot = `-- name: GetActivitySnapshot :one
SELECT runtime_id, sequence, environment_id, observed_at,
       ssh_connections, ide_connections, codex_processes, claude_processes,
       protected_processes, selected_containers, unknown_user_processes
FROM activity_snapshots
WHERE runtime_id = $1
  AND sequence = $2
`

type GetActivitySnapshotParams struct {
	RuntimeID string
	Sequence  int64
}

func (q *Queries) GetActivitySnapshot(ctx context.Context, arg GetActivitySnapshotParams) (ActivitySnapshot, error) {
	row := q.db.QueryRow(ctx, getActivitySnapshot, arg.RuntimeID, arg.Sequence)
	var i ActivitySnapshot
	err := row.Scan(
		&i.RuntimeID,
		&i.Sequence,
		&i.EnvironmentID,
		&i.ObservedAt,
		&i.SshConnections,
		&i.IdeConnections,
		&i.CodexProcesses,
		&i.ClaudeProcesses,
		&i.ProtectedProcesses,
		&i.SelectedContainers,
		&i.UnknownUserProcesses,
	)
	return i, err
}

const getAutoStopPolicyState = `-- name: GetAutoStopPolicyState :one
SELECT policy.id, policy.environment_id, policy.mode, policy.grace_period_seconds,
       policy.generation, environment.current_runtime_id
FROM auto_stop_policies policy
JOIN environments environment ON environment.id = policy.environment_id
WHERE policy.environment_id = $1
`

type GetAutoStopPolicyStateRow struct {
	ID                 string
	EnvironmentID      string
	Mode               string
	GracePeriodSeconds int32
	Generation         int64
	CurrentRuntimeID   *string
}

func (q *Queries) GetAutoStopPolicyState(ctx context.Context, environmentID string) (GetAutoStopPolicyStateRow, error) {
	row := q.db.QueryRow(ctx, getAutoStopPolicyState, environmentID)
	var i GetAutoStopPolicyStateRow
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Mode,
		&i.GracePeriodSeconds,
		&i.Generation,
		&i.CurrentRuntimeID,
	)
	return i, err
}

const getLatestActivitySnapshot = `-- name: GetLatestActivitySnapshot :one
SELECT runtime_id, sequence, environment_id, observed_at,
       ssh_connections, ide_connections, codex_processes, claude_processes,
       protected_processes, selected_containers, unknown_user_processes
FROM activity_snapshots
WHERE runtime_id = $1
ORDER BY sequence DESC
LIMIT 1
`

func (q *Queries) GetLatestActivitySnapshot(ctx context.Context, runtimeID string) (ActivitySnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestActivitySnapshot, runtimeID)
	var i ActivitySnapshot
	err := row.Scan(
		&i.RuntimeID,
		&i.Sequence,
		&i.EnvironmentID,
		&i.ObservedAt,
		&i.SshConnections,
		&i.IdeConnections,
		&i.CodexProcesses,
		&i.ClaudeProcesses,
		&i.ProtectedProcesses,
		&i.SelectedContainers,
		&i.UnknownUserProcesses,
	)
	return i, err
}

const getRuntimeStopDispatchOwner = `-- name: GetRuntimeStopDispatchOwner :one
SELECT owner_user_id, current_runtime_id
FROM environments
WHERE id = $1
`

type GetRuntimeStopDispatchOwnerRow struct {
	OwnerUserID      string
	CurrentRuntimeID *string
}

func (q *Queries) GetRuntimeStopDispatchOwner(ctx context.Context, environmentID string) (GetRuntimeStopDispatchOwnerRow, error) {
	row := q.db.QueryRow(ctx, getRuntimeStopDispatchOwner, environmentID)
	var i GetRuntimeStopDispatchOwnerRow
	err := row.Scan(&i.OwnerUserID, &i.CurrentRuntimeID)
	return i, err
}

const insertActivitySnapshot = `-- name: InsertActivitySnapshot :execrows
INSERT INTO activity_snapshots (
    runtime_id, sequence, environment_id, observed_at,
    ssh_connections, ide_connections, codex_processes, claude_processes,
    protected_processes, selected_containers, unknown_user_processes
)
SELECT
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11
FROM environments environment
JOIN runtimes runtime
  ON runtime.environment_id = environment.id
 AND runtime.id = environment.current_runtime_id
WHERE environment.id = $3
  AND runtime.id = $1
ON CONFLICT (runtime_id, sequence) DO NOTHING
`

type InsertActivitySnapshotParams struct {
	RuntimeID            string
	Sequence             int64
	EnvironmentID        string
	ObservedAt           pgtype.Timestamptz
	SshConnections       int32
	IdeConnections       int32
	CodexProcesses       int32
	ClaudeProcesses      int32
	ProtectedProcesses   int32
	SelectedContainers   int32
	UnknownUserProcesses int32
}

func (q *Queries) InsertActivitySnapshot(ctx context.Context, arg InsertActivitySnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertActivitySnapshot,
		arg.RuntimeID,
		arg.Sequence,
		arg.EnvironmentID,
		arg.ObservedAt,
		arg.SshConnections,
		arg.IdeConnections,
		arg.CodexProcesses,
		arg.ClaudeProcesses,
		arg.ProtectedProcesses,
		arg.SelectedContainers,
		arg.UnknownUserProcesses,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveAutoStopOperationTypes = `-- name: ListActiveAutoStopOperationTypes :many
SELECT type
FROM operations
WHERE environment_id = $1
  AND status IN ('queued', 'running')
  AND type IN ('environment.create', 'profile.resolve', 'runtime.start', 'runtime.replace')
ORDER BY type
`

func (q *Queries) ListActiveAutoStopOperationTypes(ctx context.Context, environmentID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveAutoStopOperationTypes, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var type_ string
		if err := rows.Scan(&type_); err != nil {
			return nil, err
		}
		items = append(items, type_)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
