// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyCreditBalanceTransaction = `-- name: ApplyCreditBalanceTransaction :one
INSERT INTO credit_balances (user_id, credits, version, updated_at)
VALUES ($1, $2, 1, $3)
ON CONFLICT (user_id) DO UPDATE
SET credits = credit_balances.credits + EXCLUDED.credits,
    version = credit_balances.version + 1,
    updated_at = EXCLUDED.updated_at
RETURNING user_id, credits, version, updated_at
`

type ApplyCreditBalanceTransactionParams struct {
	UserID    string
	Credits   int64
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ApplyCreditBalanceTransaction(ctx context.Context, arg ApplyCreditBalanceTransactionParams) (CreditBalance, error) {
	row := q.db.QueryRow(ctx, applyCreditBalanceTransaction, arg.UserID, arg.Credits, arg.UpdatedAt)
	var i CreditBalance
	err := row.Scan(
		&i.UserID,
		&i.Credits,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const closeComputeUsageInterval = `-- name: CloseComputeUsageInterval :execrows
UPDATE compute_usage_intervals
SET ended_at = $2, closure_source = $3, credit_transaction_id = $4
WHERE id = $1 AND ended_at IS NULL
`

type CloseComputeUsageIntervalParams struct {
	ID                  string
	EndedAt             pgtype.Timestamptz
	ClosureSource       *string
	CreditTransactionID *string
}

func (q *Queries) CloseComputeUsageInterval(ctx context.Context, arg CloseComputeUsageIntervalParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeComputeUsageInterval,
		arg.ID,
		arg.EndedAt,
		arg.ClosureSource,
		arg.CreditTransactionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completePolarDelivery = `-- name: CompletePolarDelivery :one
UPDATE polar_deliveries
SET delivered_at = COALESCE(delivered_at, $2)
WHERE external_id = $1
RETURNING external_id, credit_transaction_id, event_payload, created_at, delivered_at
`

type CompletePolarDeliveryParams struct {
	ExternalID  string
	DeliveredAt pgtype.Timestamptz
}

func (q *Queries) CompletePolarDelivery(ctx context.Context, arg CompletePolarDeliveryParams) (PolarDelivery, error) {
	row := q.db.QueryRow(ctx, completePolarDelivery, arg.ExternalID, arg.DeliveredAt)
	var i PolarDelivery
	err := row.Scan(
		&i.ExternalID,
		&i.CreditTransactionID,
		&i.EventPayload,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const getApplicableComputeCreditRate = `-- name: GetApplicableComputeCreditRate :one
SELECT version, resource_type, region, runtime_preset, raw_unit,
       credits_per_unit, effective_at
FROM credit_rates
WHERE resource_type = 'compute'
  AND region = $1
  AND runtime_preset = $2
  AND raw_unit = 'second'
  AND effective_at <= $3
ORDER BY effective_at DESC, version DESC
LIMIT 1
`

type GetApplicableComputeCreditRateParams struct {
	Region        string
	RuntimePreset *string
	EffectiveAt   pgtype.Timestamptz
}

func (q *Queries) GetApplicableComputeCreditRate(ctx context.Context, arg GetApplicableComputeCreditRateParams) (CreditRate, error) {
	row := q.db.QueryRow(ctx, getApplicableComputeCreditRate, arg.Region, arg.RuntimePreset, arg.EffectiveAt)
	var i CreditRate
	err := row.Scan(
		&i.Version,
		&i.ResourceType,
		&i.Region,
		&i.RuntimePreset,
		&i.RawUnit,
		&i.CreditsPerUnit,
		&i.EffectiveAt,
	)
	return i, err
}

const getComputeUsageInterval = `-- name: GetComputeUsageInterval :one
SELECT id, user_id, environment_id, runtime_id, region, runtime_preset,
       started_at, ended_at, closure_source, credit_transaction_id
FROM compute_usage_intervals
WHERE id = $1
`

func (q *Queries) GetComputeUsageInterval(ctx context.Context, id string) (ComputeUsageInterval, error) {
	row := q.db.QueryRow(ctx, getComputeUsageInterval, id)
	var i ComputeUsageInterval
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EnvironmentID,
		&i.RuntimeID,
		&i.Region,
		&i.RuntimePreset,
		&i.StartedAt,
		&i.EndedAt,
		&i.ClosureSource,
		&i.CreditTransactionID,
	)
	return i, err
}

const getComputeUsageIntervalForUpdate = `-- name: GetComputeUsageIntervalForUpdate :one
SELECT id, user_id, environment_id, runtime_id, region, runtime_preset,
       started_at, ended_at, closure_source, credit_transaction_id
FROM compute_usage_intervals
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetComputeUsageIntervalForUpdate(ctx context.Context, id string) (ComputeUsageInterval, error) {
	row := q.db.QueryRow(ctx, getComputeUsageIntervalForUpdate, id)
	var i ComputeUsageInterval
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EnvironmentID,
		&i.RuntimeID,
		&i.Region,
		&i.RuntimePreset,
		&i.StartedAt,
		&i.EndedAt,
		&i.ClosureSource,
		&i.CreditTransactionID,
	)
	return i, err
}

const getCreditBalance = `-- name: GetCreditBalance :one
SELECT user_id, credits, version, updated_at
FROM credit_balances
WHERE user_id = $1
`

func (q *Queries) GetCreditBalance(ctx context.Context, userID string) (CreditBalance, error) {
	row := q.db.QueryRow(ctx, getCreditBalance, userID)
	var i CreditBalance
	err := row.Scan(
		&i.UserID,
		&i.Credits,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const getCreditRate = `-- name: GetCreditRate :one
SELECT version, resource_type, region, runtime_preset, raw_unit,
       credits_per_unit, effective_at
FROM credit_rates
WHERE version = $1
`

func (q *Queries) GetCreditRate(ctx context.Context, version string) (CreditRate, error) {
	row := q.db.QueryRow(ctx, getCreditRate, version)
	var i CreditRate
	err := row.Scan(
		&i.Version,
		&i.ResourceType,
		&i.Region,
		&i.RuntimePreset,
		&i.RawUnit,
		&i.CreditsPerUnit,
		&i.EffectiveAt,
	)
	return i, err
}

const getCreditTransaction = `-- name: GetCreditTransaction :one
SELECT id, user_id, kind, credits, resource_type, environment_id, resource_id,
       region, raw_quantity, raw_unit, rate_version, idempotency_key,
       occurred_at, created_at
FROM credit_transactions
WHERE id = $1
`

func (q *Queries) GetCreditTransaction(ctx context.Context, id string) (CreditTransaction, error) {
	row := q.db.QueryRow(ctx, getCreditTransaction, id)
	var i CreditTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Credits,
		&i.ResourceType,
		&i.EnvironmentID,
		&i.ResourceID,
		&i.Region,
		&i.RawQuantity,
		&i.RawUnit,
		&i.RateVersion,
		&i.IdempotencyKey,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOwnedEnvironmentRuntimeForUpdate = `-- name: GetOwnedEnvironmentRuntimeForUpdate :one
SELECT region, runtime_preset, current_runtime_id
FROM environments
WHERE id = $1 AND owner_user_id = $2
FOR UPDATE
`

type GetOwnedEnvironmentRuntimeForUpdateParams struct {
	ID          string
	OwnerUserID string
}

type GetOwnedEnvironmentRuntimeForUpdateRow struct {
	Region           string
	RuntimePreset    string
	CurrentRuntimeID *string
}

func (q *Queries) GetOwnedEnvironmentRuntimeForUpdate(ctx context.Context, arg GetOwnedEnvironmentRuntimeForUpdateParams) (GetOwnedEnvironmentRuntimeForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getOwnedEnvironmentRuntimeForUpdate, arg.ID, arg.OwnerUserID)
	var i GetOwnedEnvironmentRuntimeForUpdateRow
	err := row.Scan(&i.Region, &i.RuntimePreset, &i.CurrentRuntimeID)
	return i, err
}

const getPolarCustomer = `-- name: GetPolarCustomer :one
SELECT user_id, polar_customer_id, external_event_id, observed_at
FROM polar_customers
WHERE user_id = $1
`

func (q *Queries) GetPolarCustomer(ctx context.Context, userID string) (PolarCustomer, error) {
	row := q.db.QueryRow(ctx, getPolarCustomer, userID)
	var i PolarCustomer
	err := row.Scan(
		&i.UserID,
		&i.PolarCustomerID,
		&i.ExternalEventID,
		&i.ObservedAt,
	)
	return i, err
}

const getPolarDelivery = `-- name: GetPolarDelivery :one
SELECT external_id, credit_transaction_id, event_payload, created_at, delivered_at
FROM polar_deliveries
WHERE external_id = $1
`

func (q *Queries) GetPolarDelivery(ctx context.Context, externalID string) (PolarDelivery, error) {
	row := q.db.QueryRow(ctx, getPolarDelivery, externalID)
	var i PolarDelivery
	err := row.Scan(
		&i.ExternalID,
		&i.CreditTransactionID,
		&i.EventPayload,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const getPolarWebhookReceipt = `-- name: GetPolarWebhookReceipt :one
SELECT external_event_id, event_type, payload_sha256, occurred_at, received_at
FROM polar_webhook_receipts
WHERE external_event_id = $1
`

func (q *Queries) GetPolarWebhookReceipt(ctx context.Context, externalEventID string) (PolarWebhookReceipt, error) {
	row := q.db.QueryRow(ctx, getPolarWebhookReceipt, externalEventID)
	var i PolarWebhookReceipt
	err := row.Scan(
		&i.ExternalEventID,
		&i.EventType,
		&i.PayloadSha256,
		&i.OccurredAt,
		&i.ReceivedAt,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT user_id, polar_subscription_id, polar_customer_id, status,
       current_period_start, current_period_end, cancel_at_period_end,
       canceled_at, external_event_id, observed_at
FROM subscriptions
WHERE user_id = $1
`

func (q *Queries) GetSubscription(ctx context.Context, userID string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, userID)
	var i Subscription
	err := row.Scan(
		&i.UserID,
		&i.PolarSubscriptionID,
		&i.PolarCustomerID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CanceledAt,
		&i.ExternalEventID,
		&i.ObservedAt,
	)
	return i, err
}

const insertComputeUsageInterval = `-- name: InsertComputeUsageInterval :execrows
INSERT INTO compute_usage_intervals (
    id, user_id, environment_id, runtime_id, region, runtime_preset, started_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO NOTHING
`

type InsertComputeUsageIntervalParams struct {
	ID            string
	UserID        string
	EnvironmentID string
	RuntimeID     string
	Region        string
	RuntimePreset string
	StartedAt     pgtype.Timestamptz
}

func (q *Queries) InsertComputeUsageInterval(ctx context.Context, arg InsertComputeUsageIntervalParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertComputeUsageInterval,
		arg.ID,
		arg.UserID,
		arg.EnvironmentID,
		arg.RuntimeID,
		arg.Region,
		arg.RuntimePreset,
		arg.StartedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertCreditRate = `-- name: InsertCreditRate :execrows
INSERT INTO credit_rates (
    version, resource_type, region, runtime_preset, raw_unit,
    credits_per_unit, effective_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (version) DO NOTHING
`

type InsertCreditRateParams struct {
	Version        string
	ResourceType   string
	Region         string
	RuntimePreset  *string
	RawUnit        string
	CreditsPerUnit string
	EffectiveAt    pgtype.Timestamptz
}

func (q *Queries) InsertCreditRate(ctx context.Context, arg InsertCreditRateParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCreditRate,
		arg.Version,
		arg.ResourceType,
		arg.Region,
		arg.RuntimePreset,
		arg.RawUnit,
		arg.CreditsPerUnit,
		arg.EffectiveAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertCreditTransaction = `-- name: InsertCreditTransaction :exec
INSERT INTO credit_transactions (
    id, user_id, kind, credits, resource_type, environment_id, resource_id,
    region, raw_quantity, raw_unit, rate_version, idempotency_key,
    occurred_at, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14
)
`

type InsertCreditTransactionParams struct {
	ID             string
	UserID         string
	Kind           string
	Credits        int64
	ResourceType   *string
	EnvironmentID  *string
	ResourceID     *string
	Region         *string
	RawQuantity    *string
	RawUnit        *string
	RateVersion    *string
	IdempotencyKey string
	OccurredAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) InsertCreditTransaction(ctx context.Context, arg InsertCreditTransactionParams) error {
	_, err := q.db.Exec(ctx, insertCreditTransaction,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.Credits,
		arg.ResourceType,
		arg.EnvironmentID,
		arg.ResourceID,
		arg.Region,
		arg.RawQuantity,
		arg.RawUnit,
		arg.RateVersion,
		arg.IdempotencyKey,
		arg.OccurredAt,
		arg.CreatedAt,
	)
	return err
}

const insertPolarCustomer = `-- name: InsertPolarCustomer :execrows
INSERT INTO polar_customers (
    user_id, polar_customer_id, external_event_id, observed_at
) VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO NOTHING
`

type InsertPolarCustomerParams struct {
	UserID          string
	PolarCustomerID string
	ExternalEventID string
	ObservedAt      pgtype.Timestamptz
}

func (q *Queries) InsertPolarCustomer(ctx context.Context, arg InsertPolarCustomerParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPolarCustomer,
		arg.UserID,
		arg.PolarCustomerID,
		arg.ExternalEventID,
		arg.ObservedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPolarDelivery = `-- name: InsertPolarDelivery :exec
INSERT INTO polar_deliveries (
    external_id, credit_transaction_id, event_payload, created_at
) VALUES ($1, $2, $3, $4)
`

type InsertPolarDeliveryParams struct {
	ExternalID          string
	CreditTransactionID string
	EventPayload        []byte
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) InsertPolarDelivery(ctx context.Context, arg InsertPolarDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertPolarDelivery,
		arg.ExternalID,
		arg.CreditTransactionID,
		arg.EventPayload,
		arg.CreatedAt,
	)
	return err
}

const insertPolarRecurringCreditGrant = `-- name: InsertPolarRecurringCreditGrant :exec
INSERT INTO polar_recurring_credit_grants (
    external_event_id, grant_id, user_id, polar_subscription_id,
    polar_customer_id, meter_id, credits, credited_at, credit_transaction_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertPolarRecurringCreditGrantParams struct {
	ExternalEventID     string
	GrantID             string
	UserID              string
	PolarSubscriptionID string
	PolarCustomerID     string
	MeterID             string
	Credits             int64
	CreditedAt          pgtype.Timestamptz
	CreditTransactionID string
}

func (q *Queries) InsertPolarRecurringCreditGrant(ctx context.Context, arg InsertPolarRecurringCreditGrantParams) error {
	_, err := q.db.Exec(ctx, insertPolarRecurringCreditGrant,
		arg.ExternalEventID,
		arg.GrantID,
		arg.UserID,
		arg.PolarSubscriptionID,
		arg.PolarCustomerID,
		arg.MeterID,
		arg.Credits,
		arg.CreditedAt,
		arg.CreditTransactionID,
	)
	return err
}

const insertPolarWebhookReceipt = `-- name: InsertPolarWebhookReceipt :exec
INSERT INTO polar_webhook_receipts (
    external_event_id, event_type, payload_sha256, occurred_at, received_at
) VALUES ($1, $2, $3, $4, $5)
`

type InsertPolarWebhookReceiptParams struct {
	ExternalEventID string
	EventType       string
	PayloadSha256   []byte
	OccurredAt      pgtype.Timestamptz
	ReceivedAt      pgtype.Timestamptz
}

func (q *Queries) InsertPolarWebhookReceipt(ctx context.Context, arg InsertPolarWebhookReceiptParams) error {
	_, err := q.db.Exec(ctx, insertPolarWebhookReceipt,
		arg.ExternalEventID,
		arg.EventType,
		arg.PayloadSha256,
		arg.OccurredAt,
		arg.ReceivedAt,
	)
	return err
}

const lockPolarWebhookReceipt = `-- name: LockPolarWebhookReceipt :one
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) LockPolarWebhookReceipt(ctx context.Context, hashtextextended string) (interface{}, error) {
	row := q.db.QueryRow(ctx, lockPolarWebhookReceipt, hashtextextended)
	var pg_advisory_xact_lock interface{}
	err := row.Scan(&pg_advisory_xact_lock)
	return pg_advisory_xact_lock, err
}

const upsertSubscription = `-- name: UpsertSubscription :exec
INSERT INTO subscriptions (
    user_id, polar_subscription_id, polar_customer_id, status,
    current_period_start, current_period_end, cancel_at_period_end,
    canceled_at, external_event_id, observed_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (user_id) DO UPDATE
SET polar_subscription_id = EXCLUDED.polar_subscription_id,
    polar_customer_id = EXCLUDED.polar_customer_id,
    status = EXCLUDED.status,
    current_period_start = EXCLUDED.current_period_start,
    current_period_end = EXCLUDED.current_period_end,
    cancel_at_period_end = EXCLUDED.cancel_at_period_end,
    canceled_at = EXCLUDED.canceled_at,
    external_event_id = EXCLUDED.external_event_id,
    observed_at = EXCLUDED.observed_at
WHERE subscriptions.observed_at <= EXCLUDED.observed_at
`

type UpsertSubscriptionParams struct {
	UserID              string
	PolarSubscriptionID string
	PolarCustomerID     string
	Status              string
	CurrentPeriodStart  pgtype.Timestamptz
	CurrentPeriodEnd    pgtype.Timestamptz
	CancelAtPeriodEnd   bool
	CanceledAt          pgtype.Timestamptz
	ExternalEventID     string
	ObservedAt          pgtype.Timestamptz
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertSubscription,
		arg.UserID,
		arg.PolarSubscriptionID,
		arg.PolarCustomerID,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.CancelAtPeriodEnd,
		arg.CanceledAt,
		arg.ExternalEventID,
		arg.ObservedAt,
	)
	return err
}
