// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: capsule_tags.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCapsuleTag = `-- name: GetCapsuleTag :one
SELECT owner_user_id, name, tag, digest, updated_at
FROM capsule_tags
WHERE owner_user_id = $1
  AND name = $2
  AND tag = $3
`

type GetCapsuleTagParams struct {
	OwnerUserID string
	Name        string
	Tag         string
}

func (q *Queries) GetCapsuleTag(ctx context.Context, arg GetCapsuleTagParams) (CapsuleTag, error) {
	row := q.db.QueryRow(ctx, getCapsuleTag, arg.OwnerUserID, arg.Name, arg.Tag)
	var i CapsuleTag
	err := row.Scan(
		&i.OwnerUserID,
		&i.Name,
		&i.Tag,
		&i.Digest,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCapsuleTag = `-- name: UpsertCapsuleTag :one
INSERT INTO capsule_tags (owner_user_id, name, tag, digest, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (owner_user_id, name, tag) DO UPDATE
SET digest = EXCLUDED.digest,
    updated_at = CASE
        WHEN capsule_tags.digest = EXCLUDED.digest THEN capsule_tags.updated_at
        ELSE EXCLUDED.updated_at
    END
RETURNING owner_user_id, name, tag, digest, updated_at
`

type UpsertCapsuleTagParams struct {
	OwnerUserID string
	Name        string
	Tag         string
	Digest      string
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpsertCapsuleTag(ctx context.Context, arg UpsertCapsuleTagParams) (CapsuleTag, error) {
	row := q.db.QueryRow(ctx, upsertCapsuleTag,
		arg.OwnerUserID,
		arg.Name,
		arg.Tag,
		arg.Digest,
		arg.UpdatedAt,
	)
	var i CapsuleTag
	err := row.Scan(
		&i.OwnerUserID,
		&i.Name,
		&i.Tag,
		&i.Digest,
		&i.UpdatedAt,
	)
	return i, err
}
