// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environment_create_pin.sql

package dbsql

import (
	"context"
)

const getEnvironmentCreatePin = `-- name: GetEnvironmentCreatePin :one
SELECT
    e.owner_user_id,
    e.id AS environment_id,
    e.pinned_profile_version_id
FROM operations o
JOIN environments e ON e.id = o.environment_id
WHERE o.id = $1
  AND o.type = 'environment.create'
`

type GetEnvironmentCreatePinRow struct {
	OwnerUserID            string
	EnvironmentID          string
	PinnedProfileVersionID string
}

func (q *Queries) GetEnvironmentCreatePin(ctx context.Context, operationID string) (GetEnvironmentCreatePinRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentCreatePin, operationID)
	var i GetEnvironmentCreatePinRow
	err := row.Scan(&i.OwnerUserID, &i.EnvironmentID, &i.PinnedProfileVersionID)
	return i, err
}
