// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environment_creation.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignEnvironmentSSHKeys = `-- name: AssignEnvironmentSSHKeys :execrows
INSERT INTO environment_ssh_keys (environment_id, owner_user_id, ssh_key_id)
SELECT $1, $2, key.id
FROM ssh_keys key
WHERE key.owner_user_id = $2
  AND key.revoked_at IS NULL
  AND key.id = ANY($3::text[])
`

type AssignEnvironmentSSHKeysParams struct {
	EnvironmentID string
	OwnerUserID   string
	SshKeyIds     []string
}

func (q *Queries) AssignEnvironmentSSHKeys(ctx context.Context, arg AssignEnvironmentSSHKeysParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignEnvironmentSSHKeys, arg.EnvironmentID, arg.OwnerUserID, arg.SshKeyIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const assignProjectSeed = `-- name: AssignProjectSeed :execrows
UPDATE project_seeds
SET environment_id = $1
WHERE id = $2
  AND owner_user_id = $3
  AND environment_id IS NULL
`

type AssignProjectSeedParams struct {
	EnvironmentID *string
	ProjectSeedID string
	OwnerUserID   string
}

func (q *Queries) AssignProjectSeed(ctx context.Context, arg AssignProjectSeedParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignProjectSeed, arg.EnvironmentID, arg.ProjectSeedID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeCreatedEnvironmentOperation = `-- name: CompleteCreatedEnvironmentOperation :execrows
UPDATE operations
SET status = $1,
    completed_at = $2
WHERE id = $3
  AND status IN ('queued', 'running')
`

type CompleteCreatedEnvironmentOperationParams struct {
	Status      string
	CompletedAt pgtype.Timestamptz
	OperationID string
}

func (q *Queries) CompleteCreatedEnvironmentOperation(ctx context.Context, arg CompleteCreatedEnvironmentOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeCreatedEnvironmentOperation, arg.Status, arg.CompletedAt, arg.OperationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEnvironmentCreationByKey = `-- name: GetEnvironmentCreationByKey :one
SELECT
    e.id AS environment_id,
    e.owner_user_id,
    e.name,
    e.slug,
    e.lifecycle,
    e.health,
    e.region,
    e.availability_zone,
    e.runtime_preset,
    e.pinned_profile_version_id,
    e.current_runtime_id,
    e.created_at AS environment_created_at,
    e.updated_at AS environment_updated_at,
    e.deleted_at,
    e.version,
    p.id AS policy_id,
    p.mode AS policy_mode,
    p.grace_period_seconds,
    o.id AS operation_id,
    o.type AS operation_type,
    o.status AS operation_status,
    o.idempotency_key,
    o.restate_invocation_id,
    o.input AS operation_input,
    o.created_at AS operation_created_at,
    o.completed_at AS operation_completed_at,
    ps.id AS project_seed_id
FROM operations o
JOIN environments e ON e.id = o.environment_id
JOIN auto_stop_policies p ON p.environment_id = e.id
JOIN project_seeds ps ON ps.environment_id = e.id
WHERE o.requested_by_user_id = $1
  AND o.idempotency_key = $2
`

type GetEnvironmentCreationByKeyParams struct {
	OwnerUserID    string
	IdempotencyKey string
}

type GetEnvironmentCreationByKeyRow struct {
	EnvironmentID          string
	OwnerUserID            string
	Name                   string
	Slug                   string
	Lifecycle              string
	Health                 string
	Region                 string
	AvailabilityZone       string
	RuntimePreset          string
	PinnedProfileVersionID string
	CurrentRuntimeID       *string
	EnvironmentCreatedAt   pgtype.Timestamptz
	EnvironmentUpdatedAt   pgtype.Timestamptz
	DeletedAt              pgtype.Timestamptz
	Version                int64
	PolicyID               string
	PolicyMode             string
	GracePeriodSeconds     int32
	OperationID            string
	OperationType          string
	OperationStatus        string
	IdempotencyKey         string
	RestateInvocationID    *string
	OperationInput         []byte
	OperationCreatedAt     pgtype.Timestamptz
	OperationCompletedAt   pgtype.Timestamptz
	ProjectSeedID          string
}

func (q *Queries) GetEnvironmentCreationByKey(ctx context.Context, arg GetEnvironmentCreationByKeyParams) (GetEnvironmentCreationByKeyRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentCreationByKey, arg.OwnerUserID, arg.IdempotencyKey)
	var i GetEnvironmentCreationByKeyRow
	err := row.Scan(
		&i.EnvironmentID,
		&i.OwnerUserID,
		&i.Name,
		&i.Slug,
		&i.Lifecycle,
		&i.Health,
		&i.Region,
		&i.AvailabilityZone,
		&i.RuntimePreset,
		&i.PinnedProfileVersionID,
		&i.CurrentRuntimeID,
		&i.EnvironmentCreatedAt,
		&i.EnvironmentUpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.PolicyID,
		&i.PolicyMode,
		&i.GracePeriodSeconds,
		&i.OperationID,
		&i.OperationType,
		&i.OperationStatus,
		&i.IdempotencyKey,
		&i.RestateInvocationID,
		&i.OperationInput,
		&i.OperationCreatedAt,
		&i.OperationCompletedAt,
		&i.ProjectSeedID,
	)
	return i, err
}

const getOperationCreationKeyForUpdate = `-- name: GetOperationCreationKeyForUpdate :one
SELECT requested_by_user_id, idempotency_key
FROM operations
WHERE id = $1
  AND type = 'environment.create'
FOR UPDATE
`

type GetOperationCreationKeyForUpdateRow struct {
	RequestedByUserID string
	IdempotencyKey    string
}

func (q *Queries) GetOperationCreationKeyForUpdate(ctx context.Context, operationID string) (GetOperationCreationKeyForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getOperationCreationKeyForUpdate, operationID)
	var i GetOperationCreationKeyForUpdateRow
	err := row.Scan(&i.RequestedByUserID, &i.IdempotencyKey)
	return i, err
}

const getPendingEnvironmentCreate = `-- name: GetPendingEnvironmentCreate :one
SELECT o.id AS operation_id, e.id AS environment_id, e.region, e.availability_zone, e.runtime_preset
FROM workflow_outbox outbox
JOIN operations o ON o.id = outbox.operation_id
JOIN environments e ON e.id = o.environment_id
WHERE outbox.operation_id = $1
  AND outbox.started_at IS NULL
`

type GetPendingEnvironmentCreateRow struct {
	OperationID      string
	EnvironmentID    string
	Region           string
	AvailabilityZone string
	RuntimePreset    string
}

func (q *Queries) GetPendingEnvironmentCreate(ctx context.Context, operationID string) (GetPendingEnvironmentCreateRow, error) {
	row := q.db.QueryRow(ctx, getPendingEnvironmentCreate, operationID)
	var i GetPendingEnvironmentCreateRow
	err := row.Scan(
		&i.OperationID,
		&i.EnvironmentID,
		&i.Region,
		&i.AvailabilityZone,
		&i.RuntimePreset,
	)
	return i, err
}

const insertAutoStopPolicy = `-- name: InsertAutoStopPolicy :exec
INSERT INTO auto_stop_policies (
    id, environment_id, mode, grace_period_seconds
) VALUES (
    $1, $2, $3, $4
)
`

type InsertAutoStopPolicyParams struct {
	ID                 string
	EnvironmentID      string
	Mode               string
	GracePeriodSeconds int32
}

func (q *Queries) InsertAutoStopPolicy(ctx context.Context, arg InsertAutoStopPolicyParams) error {
	_, err := q.db.Exec(ctx, insertAutoStopPolicy,
		arg.ID,
		arg.EnvironmentID,
		arg.Mode,
		arg.GracePeriodSeconds,
	)
	return err
}

const insertEnvironment = `-- name: InsertEnvironment :execrows
INSERT INTO environments (
    id, owner_user_id, name, slug, lifecycle, health, region, availability_zone,
    runtime_preset, pinned_profile_version_id, current_runtime_id, created_at,
    updated_at, deleted_at, version
)
SELECT
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11,
    $12, $13, $14, $15
FROM profile_versions pv
JOIN profiles profile ON profile.id = pv.profile_id
WHERE pv.id = $10
  AND profile.owner_user_id = $2
`

type InsertEnvironmentParams struct {
	ID                     string
	OwnerUserID            string
	Name                   string
	Slug                   string
	Lifecycle              string
	Health                 string
	Region                 string
	AvailabilityZone       string
	RuntimePreset          string
	PinnedProfileVersionID string
	CurrentRuntimeID       *string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	DeletedAt              pgtype.Timestamptz
	Version                int64
}

func (q *Queries) InsertEnvironment(ctx context.Context, arg InsertEnvironmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertEnvironment,
		arg.ID,
		arg.OwnerUserID,
		arg.Name,
		arg.Slug,
		arg.Lifecycle,
		arg.Health,
		arg.Region,
		arg.AvailabilityZone,
		arg.RuntimePreset,
		arg.PinnedProfileVersionID,
		arg.CurrentRuntimeID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertEnvironmentCreateOutbox = `-- name: InsertEnvironmentCreateOutbox :exec
INSERT INTO workflow_outbox (operation_id, kind, created_at)
VALUES ($1, 'environment.create', $2)
`

type InsertEnvironmentCreateOutboxParams struct {
	OperationID string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertEnvironmentCreateOutbox(ctx context.Context, arg InsertEnvironmentCreateOutboxParams) error {
	_, err := q.db.Exec(ctx, insertEnvironmentCreateOutbox, arg.OperationID, arg.CreatedAt)
	return err
}

const insertOperation = `-- name: InsertOperation :exec
INSERT INTO operations (
    id, environment_id, type, status, requested_by_user_id, idempotency_key,
    restate_invocation_id, input, created_at, completed_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8, $9,
    $10
)
`

type InsertOperationParams struct {
	ID                  string
	EnvironmentID       string
	Type                string
	Status              string
	RequestedByUserID   string
	IdempotencyKey      string
	RestateInvocationID *string
	Input               []byte
	CreatedAt           pgtype.Timestamptz
	CompletedAt         pgtype.Timestamptz
}

func (q *Queries) InsertOperation(ctx context.Context, arg InsertOperationParams) error {
	_, err := q.db.Exec(ctx, insertOperation,
		arg.ID,
		arg.EnvironmentID,
		arg.Type,
		arg.Status,
		arg.RequestedByUserID,
		arg.IdempotencyKey,
		arg.RestateInvocationID,
		arg.Input,
		arg.CreatedAt,
		arg.CompletedAt,
	)
	return err
}

const listEnvironmentSSHKeyIDs = `-- name: ListEnvironmentSSHKeyIDs :many
SELECT ssh_key_id
FROM environment_ssh_keys
WHERE environment_id = $1
ORDER BY ssh_key_id
`

func (q *Queries) ListEnvironmentSSHKeyIDs(ctx context.Context, environmentID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listEnvironmentSSHKeyIDs, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var ssh_key_id string
		if err := rows.Scan(&ssh_key_id); err != nil {
			return nil, err
		}
		items = append(items, ssh_key_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingEnvironmentCreates = `-- name: ListPendingEnvironmentCreates :many
SELECT o.id AS operation_id, e.id AS environment_id, e.region, e.availability_zone, e.runtime_preset
FROM workflow_outbox outbox
JOIN operations o ON o.id = outbox.operation_id
JOIN environments e ON e.id = o.environment_id
WHERE outbox.started_at IS NULL
ORDER BY outbox.created_at, outbox.operation_id
LIMIT $1
`

type ListPendingEnvironmentCreatesRow struct {
	OperationID      string
	EnvironmentID    string
	Region           string
	AvailabilityZone string
	RuntimePreset    string
}

func (q *Queries) ListPendingEnvironmentCreates(ctx context.Context, limitCount int32) ([]ListPendingEnvironmentCreatesRow, error) {
	rows, err := q.db.Query(ctx, listPendingEnvironmentCreates, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingEnvironmentCreatesRow{}
	for rows.Next() {
		var i ListPendingEnvironmentCreatesRow
		if err := rows.Scan(
			&i.OperationID,
			&i.EnvironmentID,
			&i.Region,
			&i.AvailabilityZone,
			&i.RuntimePreset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEnvironmentCreation = `-- name: LockEnvironmentCreation :one
SELECT pg_advisory_xact_lock(
    hashtextextended($1 || E'\x1f' || $2, 0)
)
`

type LockEnvironmentCreationParams struct {
	OwnerUserID    *string
	IdempotencyKey *string
}

func (q *Queries) LockEnvironmentCreation(ctx context.Context, arg LockEnvironmentCreationParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, lockEnvironmentCreation, arg.OwnerUserID, arg.IdempotencyKey)
	var pg_advisory_xact_lock interface{}
	err := row.Scan(&pg_advisory_xact_lock)
	return pg_advisory_xact_lock, err
}

const markEnvironmentCreateOutboxStarted = `-- name: MarkEnvironmentCreateOutboxStarted :execrows
UPDATE workflow_outbox
SET started_at = COALESCE(started_at, $1),
    restate_invocation_id = $2
WHERE operation_id = $3
  AND (started_at IS NULL OR restate_invocation_id = $2)
`

type MarkEnvironmentCreateOutboxStartedParams struct {
	StartedAt           pgtype.Timestamptz
	RestateInvocationID *string
	OperationID         string
}

func (q *Queries) MarkEnvironmentCreateOutboxStarted(ctx context.Context, arg MarkEnvironmentCreateOutboxStartedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markEnvironmentCreateOutboxStarted, arg.StartedAt, arg.RestateInvocationID, arg.OperationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordOperationRestateInvocation = `-- name: RecordOperationRestateInvocation :execrows
UPDATE operations
SET restate_invocation_id = $1
WHERE id = $2
  AND (restate_invocation_id IS NULL OR restate_invocation_id = $1)
`

type RecordOperationRestateInvocationParams struct {
	RestateInvocationID *string
	OperationID         string
}

func (q *Queries) RecordOperationRestateInvocation(ctx context.Context, arg RecordOperationRestateInvocationParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordOperationRestateInvocation, arg.RestateInvocationID, arg.OperationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCreatedEnvironment = `-- name: UpdateCreatedEnvironment :execrows
UPDATE environments
SET lifecycle = $1,
    health = $2,
    updated_at = $3,
    version = $4
WHERE id = $5
  AND version = $6
`

type UpdateCreatedEnvironmentParams struct {
	Lifecycle      string
	Health         string
	UpdatedAt      pgtype.Timestamptz
	NextVersion    int64
	EnvironmentID  string
	CurrentVersion int64
}

func (q *Queries) UpdateCreatedEnvironment(ctx context.Context, arg UpdateCreatedEnvironmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCreatedEnvironment,
		arg.Lifecycle,
		arg.Health,
		arg.UpdatedAt,
		arg.NextVersion,
		arg.EnvironmentID,
		arg.CurrentVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
