// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments_read.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOwnedEnvironmentDetail = `-- name: GetOwnedEnvironmentDetail :one
SELECT
    e.id, e.owner_user_id, e.name, e.slug, e.lifecycle, e.health,
    e.region AS environment_region, e.availability_zone AS environment_availability_zone,
    e.runtime_preset AS environment_runtime_preset, e.pinned_profile_version_id,
    e.capsule_lock_id, e.upgrade_policy, e.current_runtime_id,
    e.created_at AS environment_created_at, e.updated_at AS environment_updated_at,
    e.deleted_at, e.version AS environment_version,
    p.id AS auto_stop_policy_id, p.mode AS auto_stop_mode, p.grace_period_seconds,
    active_op.id AS active_operation_id
FROM environments e
JOIN auto_stop_policies p ON p.environment_id = e.id
LEFT JOIN operations active_op
    ON active_op.environment_id = e.id AND active_op.status IN ('queued', 'running')
WHERE e.id = $1 AND e.owner_user_id = $2
`

type GetOwnedEnvironmentDetailParams struct {
	EnvironmentID string
	OwnerUserID   string
}

type GetOwnedEnvironmentDetailRow struct {
	ID                          string
	OwnerUserID                 string
	Name                        string
	Slug                        string
	Lifecycle                   string
	Health                      string
	EnvironmentRegion           string
	EnvironmentAvailabilityZone string
	EnvironmentRuntimePreset    string
	PinnedProfileVersionID      string
	CapsuleLockID               *string
	UpgradePolicy               string
	CurrentRuntimeID            *string
	EnvironmentCreatedAt        pgtype.Timestamptz
	EnvironmentUpdatedAt        pgtype.Timestamptz
	DeletedAt                   pgtype.Timestamptz
	EnvironmentVersion          int64
	AutoStopPolicyID            string
	AutoStopMode                string
	GracePeriodSeconds          int32
	ActiveOperationID           *string
}

func (q *Queries) GetOwnedEnvironmentDetail(ctx context.Context, arg GetOwnedEnvironmentDetailParams) (GetOwnedEnvironmentDetailRow, error) {
	row := q.db.QueryRow(ctx, getOwnedEnvironmentDetail, arg.EnvironmentID, arg.OwnerUserID)
	var i GetOwnedEnvironmentDetailRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Slug,
		&i.Lifecycle,
		&i.Health,
		&i.EnvironmentRegion,
		&i.EnvironmentAvailabilityZone,
		&i.EnvironmentRuntimePreset,
		&i.PinnedProfileVersionID,
		&i.CapsuleLockID,
		&i.UpgradePolicy,
		&i.CurrentRuntimeID,
		&i.EnvironmentCreatedAt,
		&i.EnvironmentUpdatedAt,
		&i.DeletedAt,
		&i.EnvironmentVersion,
		&i.AutoStopPolicyID,
		&i.AutoStopMode,
		&i.GracePeriodSeconds,
		&i.ActiveOperationID,
	)
	return i, err
}

const getRuntimeByID = `-- name: GetRuntimeByID :one
SELECT id, environment_id, sequence, status, runtime_preset, region, availability_zone,
       image_version, provider_instance_ref, private_address, boot_id,
       started_at, stopped_at, retired_at, created_at, updated_at, version
FROM runtimes
WHERE id = $1
`

type GetRuntimeByIDRow struct {
	ID                  string
	EnvironmentID       string
	Sequence            int64
	Status              string
	RuntimePreset       string
	Region              string
	AvailabilityZone    string
	ImageVersion        string
	ProviderInstanceRef *string
	PrivateAddress      *string
	BootID              *string
	StartedAt           pgtype.Timestamptz
	StoppedAt           pgtype.Timestamptz
	RetiredAt           pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Version             int64
}

func (q *Queries) GetRuntimeByID(ctx context.Context, runtimeID string) (GetRuntimeByIDRow, error) {
	row := q.db.QueryRow(ctx, getRuntimeByID, runtimeID)
	var i GetRuntimeByIDRow
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Sequence,
		&i.Status,
		&i.RuntimePreset,
		&i.Region,
		&i.AvailabilityZone,
		&i.ImageVersion,
		&i.ProviderInstanceRef,
		&i.PrivateAddress,
		&i.BootID,
		&i.StartedAt,
		&i.StoppedAt,
		&i.RetiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listOwnedEnvironmentDetails = `-- name: ListOwnedEnvironmentDetails :many
SELECT
    e.id, e.owner_user_id, e.name, e.slug, e.lifecycle, e.health,
    e.region AS environment_region, e.availability_zone AS environment_availability_zone,
    e.runtime_preset AS environment_runtime_preset, e.pinned_profile_version_id,
    e.capsule_lock_id, e.upgrade_policy, e.current_runtime_id,
    e.created_at AS environment_created_at, e.updated_at AS environment_updated_at,
    e.deleted_at, e.version AS environment_version,
    p.id AS auto_stop_policy_id, p.mode AS auto_stop_mode, p.grace_period_seconds,
    active_op.id AS active_operation_id
FROM environments e
JOIN auto_stop_policies p ON p.environment_id = e.id
LEFT JOIN operations active_op
    ON active_op.environment_id = e.id AND active_op.status IN ('queued', 'running')
WHERE e.owner_user_id = $1
ORDER BY e.created_at, e.id
`

type ListOwnedEnvironmentDetailsRow struct {
	ID                          string
	OwnerUserID                 string
	Name                        string
	Slug                        string
	Lifecycle                   string
	Health                      string
	EnvironmentRegion           string
	EnvironmentAvailabilityZone string
	EnvironmentRuntimePreset    string
	PinnedProfileVersionID      string
	CapsuleLockID               *string
	UpgradePolicy               string
	CurrentRuntimeID            *string
	EnvironmentCreatedAt        pgtype.Timestamptz
	EnvironmentUpdatedAt        pgtype.Timestamptz
	DeletedAt                   pgtype.Timestamptz
	EnvironmentVersion          int64
	AutoStopPolicyID            string
	AutoStopMode                string
	GracePeriodSeconds          int32
	ActiveOperationID           *string
}

func (q *Queries) ListOwnedEnvironmentDetails(ctx context.Context, ownerUserID string) ([]ListOwnedEnvironmentDetailsRow, error) {
	rows, err := q.db.Query(ctx, listOwnedEnvironmentDetails, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnedEnvironmentDetailsRow{}
	for rows.Next() {
		var i ListOwnedEnvironmentDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.Slug,
			&i.Lifecycle,
			&i.Health,
			&i.EnvironmentRegion,
			&i.EnvironmentAvailabilityZone,
			&i.EnvironmentRuntimePreset,
			&i.PinnedProfileVersionID,
			&i.CapsuleLockID,
			&i.UpgradePolicy,
			&i.CurrentRuntimeID,
			&i.EnvironmentCreatedAt,
			&i.EnvironmentUpdatedAt,
			&i.DeletedAt,
			&i.EnvironmentVersion,
			&i.AutoStopPolicyID,
			&i.AutoStopMode,
			&i.GracePeriodSeconds,
			&i.ActiveOperationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
