// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environment_state.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertEnvironmentStateBackend = `-- name: InsertEnvironmentStateBackend :exec
INSERT INTO provider_resources (
    id, environment_id, operation_id, provider, region, resource_type,
    provider_id, metadata, created_at, deleted_at
) VALUES (
    $1, $2, $3,
    $4, $5, 'data_volume', $6,
    $7, $8, $9
)
`

type InsertEnvironmentStateBackendParams struct {
	ID            string
	EnvironmentID string
	OperationID   string
	Provider      string
	Region        string
	ProviderID    string
	Metadata      []byte
	CreatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

func (q *Queries) InsertEnvironmentStateBackend(ctx context.Context, arg InsertEnvironmentStateBackendParams) error {
	_, err := q.db.Exec(ctx, insertEnvironmentStateBackend,
		arg.ID,
		arg.EnvironmentID,
		arg.OperationID,
		arg.Provider,
		arg.Region,
		arg.ProviderID,
		arg.Metadata,
		arg.CreatedAt,
		arg.DeletedAt,
	)
	return err
}

const insertEnvironmentStateComponent = `-- name: InsertEnvironmentStateComponent :exec
INSERT INTO state_components (
    id, environment_id, kind, durability, mount_path, backend_resource_id,
    backend_resource_type, health, observed_digest, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, 'data_volume',
    $7, $8, $9, $10
)
`

type InsertEnvironmentStateComponentParams struct {
	ID                string
	EnvironmentID     string
	Kind              string
	Durability        string
	MountPath         string
	BackendResourceID string
	Health            string
	ObservedDigest    *string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) InsertEnvironmentStateComponent(ctx context.Context, arg InsertEnvironmentStateComponentParams) error {
	_, err := q.db.Exec(ctx, insertEnvironmentStateComponent,
		arg.ID,
		arg.EnvironmentID,
		arg.Kind,
		arg.Durability,
		arg.MountPath,
		arg.BackendResourceID,
		arg.Health,
		arg.ObservedDigest,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listEnvironmentStateBackendsByOperation = `-- name: ListEnvironmentStateBackendsByOperation :many
SELECT id, environment_id, operation_id, provider, region, provider_id,
       metadata, created_at, deleted_at
FROM provider_resources
WHERE operation_id = $1
ORDER BY created_at, id
`

type ListEnvironmentStateBackendsByOperationRow struct {
	ID            string
	EnvironmentID string
	OperationID   string
	Provider      string
	Region        string
	ProviderID    string
	Metadata      []byte
	CreatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

func (q *Queries) ListEnvironmentStateBackendsByOperation(ctx context.Context, operationID string) ([]ListEnvironmentStateBackendsByOperationRow, error) {
	rows, err := q.db.Query(ctx, listEnvironmentStateBackendsByOperation, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvironmentStateBackendsByOperationRow{}
	for rows.Next() {
		var i ListEnvironmentStateBackendsByOperationRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.OperationID,
			&i.Provider,
			&i.Region,
			&i.ProviderID,
			&i.Metadata,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentStateComponents = `-- name: ListEnvironmentStateComponents :many
SELECT id, environment_id, kind, durability, mount_path, backend_resource_id,
       health, observed_digest, created_at, updated_at
FROM state_components
WHERE environment_id = $1
ORDER BY CASE kind
    WHEN 'workspace' THEN 1
    WHEN 'home' THEN 2
    WHEN 'services' THEN 3
    WHEN 'cache' THEN 4
END
`

type ListEnvironmentStateComponentsRow struct {
	ID                string
	EnvironmentID     string
	Kind              string
	Durability        string
	MountPath         string
	BackendResourceID string
	Health            string
	ObservedDigest    *string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) ListEnvironmentStateComponents(ctx context.Context, environmentID string) ([]ListEnvironmentStateComponentsRow, error) {
	rows, err := q.db.Query(ctx, listEnvironmentStateComponents, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvironmentStateComponentsRow{}
	for rows.Next() {
		var i ListEnvironmentStateComponentsRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Kind,
			&i.Durability,
			&i.MountPath,
			&i.BackendResourceID,
			&i.Health,
			&i.ObservedDigest,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
