// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environment_materializations.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEnvironmentMaterializations = `-- name: DeleteEnvironmentMaterializations :execrows
DELETE FROM environment_materializations
WHERE environment_id = $1
`

func (q *Queries) DeleteEnvironmentMaterializations(ctx context.Context, environmentID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEnvironmentMaterializations, environmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCapsuleLockForEnvironment = `-- name: GetCapsuleLockForEnvironment :one
SELECT id, environment_id, profile_version_id, project_capsule_digest, digest,
       capsules, resolved_components, created_at
FROM capsule_locks
WHERE id = $1
  AND environment_id = $2
`

type GetCapsuleLockForEnvironmentParams struct {
	LockID        string
	EnvironmentID string
}

func (q *Queries) GetCapsuleLockForEnvironment(ctx context.Context, arg GetCapsuleLockForEnvironmentParams) (CapsuleLock, error) {
	row := q.db.QueryRow(ctx, getCapsuleLockForEnvironment, arg.LockID, arg.EnvironmentID)
	var i CapsuleLock
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProfileVersionID,
		&i.ProjectCapsuleDigest,
		&i.Digest,
		&i.Capsules,
		&i.ResolvedComponents,
		&i.CreatedAt,
	)
	return i, err
}

const getEnvironmentPin = `-- name: GetEnvironmentPin :one
SELECT id AS environment_id, capsule_lock_id, upgrade_policy
FROM environments
WHERE id = $1
`

type GetEnvironmentPinRow struct {
	EnvironmentID string
	CapsuleLockID *string
	UpgradePolicy string
}

func (q *Queries) GetEnvironmentPin(ctx context.Context, environmentID string) (GetEnvironmentPinRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentPin, environmentID)
	var i GetEnvironmentPinRow
	err := row.Scan(&i.EnvironmentID, &i.CapsuleLockID, &i.UpgradePolicy)
	return i, err
}

const listEnvironmentMaterializations = `-- name: ListEnvironmentMaterializations :many
SELECT environment_id, lock_id, id, lock_digest, capsule_digest, component_id, component_digest,
       adapter_id, adapter_version, target_agent_version, scope, component_type, trust_class,
       non_secret_overrides_digest, secret_version_identifiers, effective_cache_key,
       mode, root, target, selector, directory, file_paths,
       last_applied_digest, observed_digest, credential_requirement_digest, created_at, updated_at
FROM environment_materializations
WHERE environment_id = $1
ORDER BY component_id
`

func (q *Queries) ListEnvironmentMaterializations(ctx context.Context, environmentID string) ([]EnvironmentMaterialization, error) {
	rows, err := q.db.Query(ctx, listEnvironmentMaterializations, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvironmentMaterialization{}
	for rows.Next() {
		var i EnvironmentMaterialization
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.LockID,
			&i.ID,
			&i.LockDigest,
			&i.CapsuleDigest,
			&i.ComponentID,
			&i.ComponentDigest,
			&i.AdapterID,
			&i.AdapterVersion,
			&i.TargetAgentVersion,
			&i.Scope,
			&i.ComponentType,
			&i.TrustClass,
			&i.NonSecretOverridesDigest,
			&i.SecretVersionIdentifiers,
			&i.EffectiveCacheKey,
			&i.Mode,
			&i.Root,
			&i.Target,
			&i.Selector,
			&i.Directory,
			&i.FilePaths,
			&i.LastAppliedDigest,
			&i.ObservedDigest,
			&i.CredentialRequirementDigest,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEnvironmentMaterialization = `-- name: UpsertEnvironmentMaterialization :execrows
INSERT INTO environment_materializations (
    environment_id, lock_id, id, lock_digest, capsule_digest, component_id, component_digest,
    adapter_id, adapter_version, target_agent_version, scope, component_type, trust_class,
    non_secret_overrides_digest, secret_version_identifiers, effective_cache_key,
    mode, root, target, selector, directory, file_paths,
    last_applied_digest, observed_digest, credential_requirement_digest, created_at, updated_at
)
SELECT
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13,
    $14, $15, $16,
    $17, $18, $19, $20, $21, $22,
    $23, $24, $25,
    $26, $27
FROM capsule_locks
WHERE capsule_locks.id = $2
  AND capsule_locks.environment_id = $1
ON CONFLICT (environment_id, component_id) DO UPDATE
SET lock_id = EXCLUDED.lock_id,
    id = EXCLUDED.id,
    lock_digest = EXCLUDED.lock_digest,
    capsule_digest = EXCLUDED.capsule_digest,
    component_digest = EXCLUDED.component_digest,
    adapter_id = EXCLUDED.adapter_id,
    adapter_version = EXCLUDED.adapter_version,
    target_agent_version = EXCLUDED.target_agent_version,
    scope = EXCLUDED.scope,
    component_type = EXCLUDED.component_type,
    trust_class = EXCLUDED.trust_class,
    non_secret_overrides_digest = EXCLUDED.non_secret_overrides_digest,
    secret_version_identifiers = EXCLUDED.secret_version_identifiers,
    effective_cache_key = EXCLUDED.effective_cache_key,
    mode = EXCLUDED.mode,
    root = EXCLUDED.root,
    target = EXCLUDED.target,
    selector = EXCLUDED.selector,
    directory = EXCLUDED.directory,
    file_paths = EXCLUDED.file_paths,
    last_applied_digest = EXCLUDED.last_applied_digest,
    observed_digest = EXCLUDED.observed_digest,
    credential_requirement_digest = EXCLUDED.credential_requirement_digest,
    updated_at = EXCLUDED.updated_at
`

type UpsertEnvironmentMaterializationParams struct {
	EnvironmentID               string
	LockID                      string
	ID                          *string
	LockDigest                  string
	CapsuleDigest               string
	ComponentID                 string
	ComponentDigest             string
	AdapterID                   string
	AdapterVersion              string
	TargetAgentVersion          string
	Scope                       string
	ComponentType               string
	TrustClass                  string
	NonSecretOverridesDigest    *string
	SecretVersionIdentifiers    []byte
	EffectiveCacheKey           string
	Mode                        *string
	Root                        *string
	Target                      *string
	Selector                    *string
	Directory                   bool
	FilePaths                   []byte
	LastAppliedDigest           *string
	ObservedDigest              *string
	CredentialRequirementDigest *string
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
}

func (q *Queries) UpsertEnvironmentMaterialization(ctx context.Context, arg UpsertEnvironmentMaterializationParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertEnvironmentMaterialization,
		arg.EnvironmentID,
		arg.LockID,
		arg.ID,
		arg.LockDigest,
		arg.CapsuleDigest,
		arg.ComponentID,
		arg.ComponentDigest,
		arg.AdapterID,
		arg.AdapterVersion,
		arg.TargetAgentVersion,
		arg.Scope,
		arg.ComponentType,
		arg.TrustClass,
		arg.NonSecretOverridesDigest,
		arg.SecretVersionIdentifiers,
		arg.EffectiveCacheKey,
		arg.Mode,
		arg.Root,
		arg.Target,
		arg.Selector,
		arg.Directory,
		arg.FilePaths,
		arg.LastAppliedDigest,
		arg.ObservedDigest,
		arg.CredentialRequirementDigest,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertEnvironmentPin = `-- name: UpsertEnvironmentPin :one
UPDATE environments
SET capsule_lock_id = $1,
    upgrade_policy = $2
WHERE environments.id = $3
  AND (
      $1::text IS NULL
      OR EXISTS (
          SELECT 1
          FROM capsule_locks
          WHERE capsule_locks.id = $1
            AND capsule_locks.environment_id = environments.id
      )
  )
RETURNING environments.id AS environment_id, capsule_lock_id, upgrade_policy
`

type UpsertEnvironmentPinParams struct {
	CapsuleLockID *string
	UpgradePolicy string
	EnvironmentID string
}

type UpsertEnvironmentPinRow struct {
	EnvironmentID string
	CapsuleLockID *string
	UpgradePolicy string
}

func (q *Queries) UpsertEnvironmentPin(ctx context.Context, arg UpsertEnvironmentPinParams) (UpsertEnvironmentPinRow, error) {
	row := q.db.QueryRow(ctx, upsertEnvironmentPin, arg.CapsuleLockID, arg.UpgradePolicy, arg.EnvironmentID)
	var i UpsertEnvironmentPinRow
	err := row.Scan(&i.EnvironmentID, &i.CapsuleLockID, &i.UpgradePolicy)
	return i, err
}
