// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations_read.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOwnedOperation = `-- name: GetOwnedOperation :one
SELECT id, environment_id, type, status, requested_by_user_id, idempotency_key,
       restate_invocation_id, input, created_at, completed_at
FROM operations
WHERE id = $1 AND requested_by_user_id = $2
`

type GetOwnedOperationParams struct {
	OperationID string
	OwnerUserID string
}

type GetOwnedOperationRow struct {
	ID                  string
	EnvironmentID       string
	Type                string
	Status              string
	RequestedByUserID   string
	IdempotencyKey      string
	RestateInvocationID *string
	Input               []byte
	CreatedAt           pgtype.Timestamptz
	CompletedAt         pgtype.Timestamptz
}

func (q *Queries) GetOwnedOperation(ctx context.Context, arg GetOwnedOperationParams) (GetOwnedOperationRow, error) {
	row := q.db.QueryRow(ctx, getOwnedOperation, arg.OperationID, arg.OwnerUserID)
	var i GetOwnedOperationRow
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Type,
		&i.Status,
		&i.RequestedByUserID,
		&i.IdempotencyKey,
		&i.RestateInvocationID,
		&i.Input,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listOperationSteps = `-- name: ListOperationSteps :many
SELECT step_key, status, summary
FROM operation_steps
WHERE operation_id = $1
ORDER BY step_key
`

type ListOperationStepsRow struct {
	StepKey string
	Status  string
	Summary string
}

func (q *Queries) ListOperationSteps(ctx context.Context, operationID string) ([]ListOperationStepsRow, error) {
	rows, err := q.db.Query(ctx, listOperationSteps, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOperationStepsRow{}
	for rows.Next() {
		var i ListOperationStepsRow
		if err := rows.Scan(&i.StepKey, &i.Status, &i.Summary); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnedEnvironmentOperations = `-- name: ListOwnedEnvironmentOperations :many
SELECT o.id, o.environment_id, o.type, o.status, o.created_at
FROM operations o
JOIN environments e ON e.id = o.environment_id
WHERE e.id = $1 AND e.owner_user_id = $2
  AND (
    NOT $3::bool
    OR (o.created_at, o.id) > ($4::timestamptz, $5::text)
  )
ORDER BY o.created_at, o.id
LIMIT $6::int
`

type ListOwnedEnvironmentOperationsParams struct {
	EnvironmentID   string
	OwnerUserID     string
	HasCursor       bool
	CursorCreatedAt pgtype.Timestamptz
	CursorID        string
	RowLimit        int32
}

type ListOwnedEnvironmentOperationsRow struct {
	ID            string
	EnvironmentID string
	Type          string
	Status        string
	CreatedAt     pgtype.Timestamptz
}

// Keyset pagination: rows are ordered by (o.created_at, o.id), the same
// tuple the WHERE predicate compares against the caller's decoded cursor.
// Passing has_cursor = false selects the first page; row_limit is the
// caller's effective page size plus one, letting the store detect a next
// page without a second round trip.
func (q *Queries) ListOwnedEnvironmentOperations(ctx context.Context, arg ListOwnedEnvironmentOperationsParams) ([]ListOwnedEnvironmentOperationsRow, error) {
	rows, err := q.db.Query(ctx, listOwnedEnvironmentOperations,
		arg.EnvironmentID,
		arg.OwnerUserID,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnedEnvironmentOperationsRow{}
	for rows.Next() {
		var i ListOwnedEnvironmentOperationsRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Type,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
