// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOwnedProfileForUpdate = `-- name: GetOwnedProfileForUpdate :one
SELECT id, owner_user_id, name, slug, created_at, archived_at
FROM profiles
WHERE id = $1 AND owner_user_id = $2
FOR UPDATE
`

type GetOwnedProfileForUpdateParams struct {
	ProfileID   string
	OwnerUserID string
}

func (q *Queries) GetOwnedProfileForUpdate(ctx context.Context, arg GetOwnedProfileForUpdateParams) (Profile, error) {
	row := q.db.QueryRow(ctx, getOwnedProfileForUpdate, arg.ProfileID, arg.OwnerUserID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getProfileCreateRegistration = `-- name: GetProfileCreateRegistration :one
SELECT p.id, p.owner_user_id, p.name, p.slug, p.created_at, p.archived_at, registration.input
FROM profile_create_registrations registration
JOIN profiles p ON p.id = registration.profile_id
WHERE registration.owner_user_id = $1
  AND registration.idempotency_key = $2
`

type GetProfileCreateRegistrationParams struct {
	OwnerUserID    string
	IdempotencyKey string
}

type GetProfileCreateRegistrationRow struct {
	ID          string
	OwnerUserID string
	Name        string
	Slug        string
	CreatedAt   pgtype.Timestamptz
	ArchivedAt  pgtype.Timestamptz
	Input       []byte
}

func (q *Queries) GetProfileCreateRegistration(ctx context.Context, arg GetProfileCreateRegistrationParams) (GetProfileCreateRegistrationRow, error) {
	row := q.db.QueryRow(ctx, getProfileCreateRegistration, arg.OwnerUserID, arg.IdempotencyKey)
	var i GetProfileCreateRegistrationRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.Input,
	)
	return i, err
}

const getProfileHead = `-- name: GetProfileHead :one
SELECT id, profile_id, parent_version_id, version, digest, created_at
FROM profile_versions
WHERE profile_id = $1
ORDER BY version DESC
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetProfileHead(ctx context.Context, profileID string) (ProfileVersion, error) {
	row := q.db.QueryRow(ctx, getProfileHead, profileID)
	var i ProfileVersion
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ParentVersionID,
		&i.Version,
		&i.Digest,
		&i.CreatedAt,
	)
	return i, err
}

const getProfilePublicationRegistration = `-- name: GetProfilePublicationRegistration :one
SELECT registration.input, registration.profile_id, registration.profile_version_id
FROM profile_publication_registrations registration
WHERE registration.owner_user_id = $1
  AND registration.idempotency_key = $2
`

type GetProfilePublicationRegistrationParams struct {
	OwnerUserID    string
	IdempotencyKey string
}

type GetProfilePublicationRegistrationRow struct {
	Input            []byte
	ProfileID        string
	ProfileVersionID string
}

func (q *Queries) GetProfilePublicationRegistration(ctx context.Context, arg GetProfilePublicationRegistrationParams) (GetProfilePublicationRegistrationRow, error) {
	row := q.db.QueryRow(ctx, getProfilePublicationRegistration, arg.OwnerUserID, arg.IdempotencyKey)
	var i GetProfilePublicationRegistrationRow
	err := row.Scan(&i.Input, &i.ProfileID, &i.ProfileVersionID)
	return i, err
}

const getProfileVersion = `-- name: GetProfileVersion :one
SELECT id, profile_id, parent_version_id, version, digest, created_at
FROM profile_versions
WHERE id = $1 AND profile_id = $2
`

type GetProfileVersionParams struct {
	ProfileVersionID string
	ProfileID        string
}

func (q *Queries) GetProfileVersion(ctx context.Context, arg GetProfileVersionParams) (ProfileVersion, error) {
	row := q.db.QueryRow(ctx, getProfileVersion, arg.ProfileVersionID, arg.ProfileID)
	var i ProfileVersion
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ParentVersionID,
		&i.Version,
		&i.Digest,
		&i.CreatedAt,
	)
	return i, err
}

const insertProfile = `-- name: InsertProfile :exec
INSERT INTO profiles (id, owner_user_id, name, slug, created_at, archived_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertProfileParams struct {
	ID          string
	OwnerUserID string
	Name        string
	Slug        string
	CreatedAt   pgtype.Timestamptz
	ArchivedAt  pgtype.Timestamptz
}

func (q *Queries) InsertProfile(ctx context.Context, arg InsertProfileParams) error {
	_, err := q.db.Exec(ctx, insertProfile,
		arg.ID,
		arg.OwnerUserID,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
		arg.ArchivedAt,
	)
	return err
}

const insertProfileArtifact = `-- name: InsertProfileArtifact :exec
INSERT INTO profile_artifacts (
    id, profile_version_id, kind, source_locator, source_digest, content_digest, size_bytes, mode, sensitivity, trust, contains_executable
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11
)
`

type InsertProfileArtifactParams struct {
	ID                 string
	ProfileVersionID   string
	Kind               string
	SourceLocator      string
	SourceDigest       string
	ContentDigest      string
	SizeBytes          int64
	Mode               int32
	Sensitivity        string
	Trust              string
	ContainsExecutable bool
}

func (q *Queries) InsertProfileArtifact(ctx context.Context, arg InsertProfileArtifactParams) error {
	_, err := q.db.Exec(ctx, insertProfileArtifact,
		arg.ID,
		arg.ProfileVersionID,
		arg.Kind,
		arg.SourceLocator,
		arg.SourceDigest,
		arg.ContentDigest,
		arg.SizeBytes,
		arg.Mode,
		arg.Sensitivity,
		arg.Trust,
		arg.ContainsExecutable,
	)
	return err
}

const insertProfileCreateRegistration = `-- name: InsertProfileCreateRegistration :exec
INSERT INTO profile_create_registrations (owner_user_id, idempotency_key, input, profile_id)
VALUES ($1, $2, $3, $4)
`

type InsertProfileCreateRegistrationParams struct {
	OwnerUserID    string
	IdempotencyKey string
	Input          []byte
	ProfileID      string
}

func (q *Queries) InsertProfileCreateRegistration(ctx context.Context, arg InsertProfileCreateRegistrationParams) error {
	_, err := q.db.Exec(ctx, insertProfileCreateRegistration,
		arg.OwnerUserID,
		arg.IdempotencyKey,
		arg.Input,
		arg.ProfileID,
	)
	return err
}

const insertProfilePublicationRegistration = `-- name: InsertProfilePublicationRegistration :exec
INSERT INTO profile_publication_registrations (owner_user_id, idempotency_key, input, profile_id, profile_version_id)
VALUES ($1, $2, $3, $4, $5)
`

type InsertProfilePublicationRegistrationParams struct {
	OwnerUserID      string
	IdempotencyKey   string
	Input            []byte
	ProfileID        string
	ProfileVersionID string
}

func (q *Queries) InsertProfilePublicationRegistration(ctx context.Context, arg InsertProfilePublicationRegistrationParams) error {
	_, err := q.db.Exec(ctx, insertProfilePublicationRegistration,
		arg.OwnerUserID,
		arg.IdempotencyKey,
		arg.Input,
		arg.ProfileID,
		arg.ProfileVersionID,
	)
	return err
}

const insertProfileVersion = `-- name: InsertProfileVersion :exec
INSERT INTO profile_versions (id, profile_id, parent_version_id, version, digest, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertProfileVersionParams struct {
	ID              string
	ProfileID       string
	ParentVersionID *string
	Version         int64
	Digest          string
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) InsertProfileVersion(ctx context.Context, arg InsertProfileVersionParams) error {
	_, err := q.db.Exec(ctx, insertProfileVersion,
		arg.ID,
		arg.ProfileID,
		arg.ParentVersionID,
		arg.Version,
		arg.Digest,
		arg.CreatedAt,
	)
	return err
}

const listProfileArtifacts = `-- name: ListProfileArtifacts :many
SELECT id, profile_version_id, kind, source_locator, source_digest, content_digest, size_bytes, mode, sensitivity, trust, contains_executable
FROM profile_artifacts
WHERE profile_version_id = $1
ORDER BY id
`

func (q *Queries) ListProfileArtifacts(ctx context.Context, profileVersionID string) ([]ProfileArtifact, error) {
	rows, err := q.db.Query(ctx, listProfileArtifacts, profileVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProfileArtifact{}
	for rows.Next() {
		var i ProfileArtifact
		if err := rows.Scan(
			&i.ID,
			&i.ProfileVersionID,
			&i.Kind,
			&i.SourceLocator,
			&i.SourceDigest,
			&i.ContentDigest,
			&i.SizeBytes,
			&i.Mode,
			&i.Sensitivity,
			&i.Trust,
			&i.ContainsExecutable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProfileCreateRegistration = `-- name: LockProfileCreateRegistration :one
SELECT pg_advisory_xact_lock(
    hashtextextended('profile-create' || chr(31) || $1::text || chr(31) || $2::text, 0)
)
`

type LockProfileCreateRegistrationParams struct {
	OwnerUserID    string
	IdempotencyKey string
}

func (q *Queries) LockProfileCreateRegistration(ctx context.Context, arg LockProfileCreateRegistrationParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, lockProfileCreateRegistration, arg.OwnerUserID, arg.IdempotencyKey)
	var pg_advisory_xact_lock interface{}
	err := row.Scan(&pg_advisory_xact_lock)
	return pg_advisory_xact_lock, err
}

const lockProfilePublicationRegistration = `-- name: LockProfilePublicationRegistration :one
SELECT pg_advisory_xact_lock(
    hashtextextended('profile-publication' || chr(31) || $1::text || chr(31) || $2::text, 0)
)
`

type LockProfilePublicationRegistrationParams struct {
	OwnerUserID    string
	IdempotencyKey string
}

func (q *Queries) LockProfilePublicationRegistration(ctx context.Context, arg LockProfilePublicationRegistrationParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, lockProfilePublicationRegistration, arg.OwnerUserID, arg.IdempotencyKey)
	var pg_advisory_xact_lock interface{}
	err := row.Scan(&pg_advisory_xact_lock)
	return pg_advisory_xact_lock, err
}
