// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles_read.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOwnedProfile = `-- name: GetOwnedProfile :one
SELECT id, owner_user_id, name, slug, created_at, archived_at
FROM profiles
WHERE id = $1 AND owner_user_id = $2
`

type GetOwnedProfileParams struct {
	ProfileID   string
	OwnerUserID string
}

func (q *Queries) GetOwnedProfile(ctx context.Context, arg GetOwnedProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, getOwnedProfile, arg.ProfileID, arg.OwnerUserID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getOwnedProfileVersion = `-- name: GetOwnedProfileVersion :one
SELECT pv.id, pv.profile_id, pv.parent_version_id, pv.version, pv.digest, pv.created_at
FROM profile_versions pv
JOIN profiles p ON p.id = pv.profile_id
WHERE pv.id = $1 AND p.owner_user_id = $2
`

type GetOwnedProfileVersionParams struct {
	ProfileVersionID string
	OwnerUserID      string
}

func (q *Queries) GetOwnedProfileVersion(ctx context.Context, arg GetOwnedProfileVersionParams) (ProfileVersion, error) {
	row := q.db.QueryRow(ctx, getOwnedProfileVersion, arg.ProfileVersionID, arg.OwnerUserID)
	var i ProfileVersion
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ParentVersionID,
		&i.Version,
		&i.Digest,
		&i.CreatedAt,
	)
	return i, err
}

const getProfileHeadVersionID = `-- name: GetProfileHeadVersionID :one
SELECT pv.id
FROM profile_versions pv
WHERE pv.profile_id = $1
ORDER BY pv.version DESC
LIMIT 1
`

func (q *Queries) GetProfileHeadVersionID(ctx context.Context, profileID string) (string, error) {
	row := q.db.QueryRow(ctx, getProfileHeadVersionID, profileID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listOwnedProfiles = `-- name: ListOwnedProfiles :many
SELECT id, owner_user_id, name, slug, created_at, archived_at
FROM profiles
WHERE owner_user_id = $1
  AND (
    NOT $2::bool
    OR (created_at, id) > ($3::timestamptz, $4::text)
  )
ORDER BY created_at, id
LIMIT $5::int
`

type ListOwnedProfilesParams struct {
	OwnerUserID     string
	HasCursor       bool
	CursorCreatedAt pgtype.Timestamptz
	CursorID        string
	RowLimit        int32
}

// Keyset pagination: rows are ordered by (created_at, id), the same tuple
// the WHERE predicate compares against the caller's decoded cursor. Passing
// has_cursor = false selects the first page; row_limit is the caller's
// effective page size plus one, letting the store detect a next page
// without a second round trip.
func (q *Queries) ListOwnedProfiles(ctx context.Context, arg ListOwnedProfilesParams) ([]Profile, error) {
	rows, err := q.db.Query(ctx, listOwnedProfiles,
		arg.OwnerUserID,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Profile{}
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
