// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeProfileResolveOperation = `-- name: CompleteProfileResolveOperation :execrows
UPDATE operations
SET status = 'succeeded', completed_at = $1
WHERE id = $2
  AND type = 'profile.resolve'
  AND status IN ('queued', 'running')
`

type CompleteProfileResolveOperationParams struct {
	CompletedAt pgtype.Timestamptz
	OperationID string
}

func (q *Queries) CompleteProfileResolveOperation(ctx context.Context, arg CompleteProfileResolveOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeProfileResolveOperation, arg.CompletedAt, arg.OperationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeProfileResolveStep = `-- name: CompleteProfileResolveStep :execrows
UPDATE operation_steps
SET status = 'succeeded', completed_at = $1
WHERE operation_id = $2
  AND step_key = 'resolve'
  AND status = 'running'
`

type CompleteProfileResolveStepParams struct {
	CompletedAt pgtype.Timestamptz
	OperationID string
}

func (q *Queries) CompleteProfileResolveStep(ctx context.Context, arg CompleteProfileResolveStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeProfileResolveStep, arg.CompletedAt, arg.OperationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCapsuleLockByTarget = `-- name: GetCapsuleLockByTarget :one
SELECT id, environment_id, profile_version_id, project_capsule_digest, digest,
       capsules, resolved_components, created_at
FROM capsule_locks
WHERE environment_id = $1
  AND profile_version_id = $2
  AND project_capsule_digest = $3
`

type GetCapsuleLockByTargetParams struct {
	EnvironmentID        string
	ProfileVersionID     string
	ProjectCapsuleDigest string
}

func (q *Queries) GetCapsuleLockByTarget(ctx context.Context, arg GetCapsuleLockByTargetParams) (CapsuleLock, error) {
	row := q.db.QueryRow(ctx, getCapsuleLockByTarget, arg.EnvironmentID, arg.ProfileVersionID, arg.ProjectCapsuleDigest)
	var i CapsuleLock
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ProfileVersionID,
		&i.ProjectCapsuleDigest,
		&i.Digest,
		&i.Capsules,
		&i.ResolvedComponents,
		&i.CreatedAt,
	)
	return i, err
}

const getEnvironmentOwner = `-- name: GetEnvironmentOwner :one
SELECT owner_user_id
FROM environments
WHERE id = $1
FOR SHARE
`

func (q *Queries) GetEnvironmentOwner(ctx context.Context, environmentID string) (string, error) {
	row := q.db.QueryRow(ctx, getEnvironmentOwner, environmentID)
	var owner_user_id string
	err := row.Scan(&owner_user_id)
	return owner_user_id, err
}

const getOwnedProfileForUpdate = `-- name: GetOwnedProfileForUpdate :one
SELECT id, owner_user_id, name, slug, created_at, archived_at
FROM profiles
WHERE id = $1 AND owner_user_id = $2
FOR UPDATE
`

type GetOwnedProfileForUpdateParams struct {
	ProfileID   string
	OwnerUserID string
}

func (q *Queries) GetOwnedProfileForUpdate(ctx context.Context, arg GetOwnedProfileForUpdateParams) (Profile, error) {
	row := q.db.QueryRow(ctx, getOwnedProfileForUpdate, arg.ProfileID, arg.OwnerUserID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getProfileCreateRegistration = `-- name: GetProfileCreateRegistration :one
SELECT p.id, p.owner_user_id, p.name, p.slug, p.created_at, p.archived_at, registration.input
FROM profile_create_registrations registration
JOIN profiles p ON p.id = registration.profile_id
WHERE registration.owner_user_id = $1
  AND registration.idempotency_key = $2
`

type GetProfileCreateRegistrationParams struct {
	OwnerUserID    string
	IdempotencyKey string
}

type GetProfileCreateRegistrationRow struct {
	ID          string
	OwnerUserID string
	Name        string
	Slug        string
	CreatedAt   pgtype.Timestamptz
	ArchivedAt  pgtype.Timestamptz
	Input       []byte
}

func (q *Queries) GetProfileCreateRegistration(ctx context.Context, arg GetProfileCreateRegistrationParams) (GetProfileCreateRegistrationRow, error) {
	row := q.db.QueryRow(ctx, getProfileCreateRegistration, arg.OwnerUserID, arg.IdempotencyKey)
	var i GetProfileCreateRegistrationRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.Input,
	)
	return i, err
}

const getProfileHead = `-- name: GetProfileHead :one
SELECT id, profile_id, parent_version_id, version, digest, created_at
FROM profile_versions
WHERE profile_id = $1
ORDER BY version DESC
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetProfileHead(ctx context.Context, profileID string) (ProfileVersion, error) {
	row := q.db.QueryRow(ctx, getProfileHead, profileID)
	var i ProfileVersion
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ParentVersionID,
		&i.Version,
		&i.Digest,
		&i.CreatedAt,
	)
	return i, err
}

const getProfilePublicationRegistration = `-- name: GetProfilePublicationRegistration :one
SELECT registration.input, registration.profile_id, registration.profile_version_id
FROM profile_publication_registrations registration
WHERE registration.owner_user_id = $1
  AND registration.idempotency_key = $2
`

type GetProfilePublicationRegistrationParams struct {
	OwnerUserID    string
	IdempotencyKey string
}

type GetProfilePublicationRegistrationRow struct {
	Input            []byte
	ProfileID        string
	ProfileVersionID string
}

func (q *Queries) GetProfilePublicationRegistration(ctx context.Context, arg GetProfilePublicationRegistrationParams) (GetProfilePublicationRegistrationRow, error) {
	row := q.db.QueryRow(ctx, getProfilePublicationRegistration, arg.OwnerUserID, arg.IdempotencyKey)
	var i GetProfilePublicationRegistrationRow
	err := row.Scan(&i.Input, &i.ProfileID, &i.ProfileVersionID)
	return i, err
}

const getProfileResolveOperation = `-- name: GetProfileResolveOperation :one
SELECT id, environment_id, type, status, requested_by_user_id, idempotency_key,
       restate_invocation_id, input, created_at, completed_at
FROM operations
WHERE id = $1
  AND type = 'profile.resolve'
FOR UPDATE
`

type GetProfileResolveOperationRow struct {
	ID                  string
	EnvironmentID       string
	Type                string
	Status              string
	RequestedByUserID   string
	IdempotencyKey      string
	RestateInvocationID *string
	Input               []byte
	CreatedAt           pgtype.Timestamptz
	CompletedAt         pgtype.Timestamptz
}

func (q *Queries) GetProfileResolveOperation(ctx context.Context, operationID string) (GetProfileResolveOperationRow, error) {
	row := q.db.QueryRow(ctx, getProfileResolveOperation, operationID)
	var i GetProfileResolveOperationRow
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Type,
		&i.Status,
		&i.RequestedByUserID,
		&i.IdempotencyKey,
		&i.RestateInvocationID,
		&i.Input,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getProfileVersion = `-- name: GetProfileVersion :one
SELECT id, profile_id, parent_version_id, version, digest, created_at
FROM profile_versions
WHERE id = $1 AND profile_id = $2
`

type GetProfileVersionParams struct {
	ProfileVersionID string
	ProfileID        string
}

func (q *Queries) GetProfileVersion(ctx context.Context, arg GetProfileVersionParams) (ProfileVersion, error) {
	row := q.db.QueryRow(ctx, getProfileVersion, arg.ProfileVersionID, arg.ProfileID)
	var i ProfileVersion
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ParentVersionID,
		&i.Version,
		&i.Digest,
		&i.CreatedAt,
	)
	return i, err
}

const getProfileVersionForEnvironment = `-- name: GetProfileVersionForEnvironment :one
SELECT pv.id, pv.profile_id, pv.parent_version_id, pv.version, pv.digest, pv.created_at
FROM profile_versions pv
JOIN profiles p ON p.id = pv.profile_id
JOIN environments e ON e.owner_user_id = p.owner_user_id
WHERE e.id = $1
  AND pv.id = $2
FOR SHARE
`

type GetProfileVersionForEnvironmentParams struct {
	EnvironmentID    string
	ProfileVersionID string
}

func (q *Queries) GetProfileVersionForEnvironment(ctx context.Context, arg GetProfileVersionForEnvironmentParams) (ProfileVersion, error) {
	row := q.db.QueryRow(ctx, getProfileVersionForEnvironment, arg.EnvironmentID, arg.ProfileVersionID)
	var i ProfileVersion
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ParentVersionID,
		&i.Version,
		&i.Digest,
		&i.CreatedAt,
	)
	return i, err
}

const insertCapsuleLock = `-- name: InsertCapsuleLock :exec
INSERT INTO capsule_locks (
    id, environment_id, profile_version_id, project_capsule_digest, digest,
    capsules, resolved_components, created_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8
)
`

type InsertCapsuleLockParams struct {
	ID                   string
	EnvironmentID        string
	ProfileVersionID     string
	ProjectCapsuleDigest string
	Digest               string
	Capsules             []byte
	ResolvedComponents   []byte
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) InsertCapsuleLock(ctx context.Context, arg InsertCapsuleLockParams) error {
	_, err := q.db.Exec(ctx, insertCapsuleLock,
		arg.ID,
		arg.EnvironmentID,
		arg.ProfileVersionID,
		arg.ProjectCapsuleDigest,
		arg.Digest,
		arg.Capsules,
		arg.ResolvedComponents,
		arg.CreatedAt,
	)
	return err
}

const insertProfile = `-- name: InsertProfile :exec
INSERT INTO profiles (id, owner_user_id, name, slug, created_at, archived_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertProfileParams struct {
	ID          string
	OwnerUserID string
	Name        string
	Slug        string
	CreatedAt   pgtype.Timestamptz
	ArchivedAt  pgtype.Timestamptz
}

func (q *Queries) InsertProfile(ctx context.Context, arg InsertProfileParams) error {
	_, err := q.db.Exec(ctx, insertProfile,
		arg.ID,
		arg.OwnerUserID,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
		arg.ArchivedAt,
	)
	return err
}

const insertProfileCreateRegistration = `-- name: InsertProfileCreateRegistration :exec
INSERT INTO profile_create_registrations (owner_user_id, idempotency_key, input, profile_id)
VALUES ($1, $2, $3, $4)
`

type InsertProfileCreateRegistrationParams struct {
	OwnerUserID    string
	IdempotencyKey string
	Input          []byte
	ProfileID      string
}

func (q *Queries) InsertProfileCreateRegistration(ctx context.Context, arg InsertProfileCreateRegistrationParams) error {
	_, err := q.db.Exec(ctx, insertProfileCreateRegistration,
		arg.OwnerUserID,
		arg.IdempotencyKey,
		arg.Input,
		arg.ProfileID,
	)
	return err
}

const insertProfilePublicationRegistration = `-- name: InsertProfilePublicationRegistration :exec
INSERT INTO profile_publication_registrations (owner_user_id, idempotency_key, input, profile_id, profile_version_id)
VALUES ($1, $2, $3, $4, $5)
`

type InsertProfilePublicationRegistrationParams struct {
	OwnerUserID      string
	IdempotencyKey   string
	Input            []byte
	ProfileID        string
	ProfileVersionID string
}

func (q *Queries) InsertProfilePublicationRegistration(ctx context.Context, arg InsertProfilePublicationRegistrationParams) error {
	_, err := q.db.Exec(ctx, insertProfilePublicationRegistration,
		arg.OwnerUserID,
		arg.IdempotencyKey,
		arg.Input,
		arg.ProfileID,
		arg.ProfileVersionID,
	)
	return err
}

const insertProfileResolveOperation = `-- name: InsertProfileResolveOperation :exec
INSERT INTO operations (
    id, environment_id, type, status, requested_by_user_id, idempotency_key,
    restate_invocation_id, input, created_at, completed_at
) VALUES (
    $1, $2, 'profile.resolve', $3,
    $4, $5,
    $6, $7, $8, $9
)
`

type InsertProfileResolveOperationParams struct {
	ID                  string
	EnvironmentID       string
	Status              string
	RequestedByUserID   string
	IdempotencyKey      string
	RestateInvocationID *string
	Input               []byte
	CreatedAt           pgtype.Timestamptz
	CompletedAt         pgtype.Timestamptz
}

func (q *Queries) InsertProfileResolveOperation(ctx context.Context, arg InsertProfileResolveOperationParams) error {
	_, err := q.db.Exec(ctx, insertProfileResolveOperation,
		arg.ID,
		arg.EnvironmentID,
		arg.Status,
		arg.RequestedByUserID,
		arg.IdempotencyKey,
		arg.RestateInvocationID,
		arg.Input,
		arg.CreatedAt,
		arg.CompletedAt,
	)
	return err
}

const insertProfileResolveStep = `-- name: InsertProfileResolveStep :exec
INSERT INTO operation_steps (
    id, operation_id, step_key, status, attempt, summary, started_at
) VALUES (
    $1, $2, 'resolve', 'running', 1, 'Resolve Profile Version into Capsule Lock', $3
)
`

type InsertProfileResolveStepParams struct {
	ID          string
	OperationID string
	StartedAt   pgtype.Timestamptz
}

func (q *Queries) InsertProfileResolveStep(ctx context.Context, arg InsertProfileResolveStepParams) error {
	_, err := q.db.Exec(ctx, insertProfileResolveStep, arg.ID, arg.OperationID, arg.StartedAt)
	return err
}

const insertProfileVersion = `-- name: InsertProfileVersion :exec
INSERT INTO profile_versions (id, profile_id, parent_version_id, version, digest, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertProfileVersionParams struct {
	ID              string
	ProfileID       string
	ParentVersionID *string
	Version         int64
	Digest          string
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) InsertProfileVersion(ctx context.Context, arg InsertProfileVersionParams) error {
	_, err := q.db.Exec(ctx, insertProfileVersion,
		arg.ID,
		arg.ProfileID,
		arg.ParentVersionID,
		arg.Version,
		arg.Digest,
		arg.CreatedAt,
	)
	return err
}

const insertProfileVersionCapsuleRef = `-- name: InsertProfileVersionCapsuleRef :exec
INSERT INTO profile_version_capsule_refs (profile_version_id, ordinal, ref, freshness_policy, exclusions)
VALUES ($1, $2, $3, $4, $5)
`

type InsertProfileVersionCapsuleRefParams struct {
	ProfileVersionID string
	Ordinal          int32
	Ref              string
	FreshnessPolicy  string
	Exclusions       []byte
}

func (q *Queries) InsertProfileVersionCapsuleRef(ctx context.Context, arg InsertProfileVersionCapsuleRefParams) error {
	_, err := q.db.Exec(ctx, insertProfileVersionCapsuleRef,
		arg.ProfileVersionID,
		arg.Ordinal,
		arg.Ref,
		arg.FreshnessPolicy,
		arg.Exclusions,
	)
	return err
}

const listProfileVersionCapsuleRefs = `-- name: ListProfileVersionCapsuleRefs :many
SELECT ordinal, ref, freshness_policy, exclusions
FROM profile_version_capsule_refs
WHERE profile_version_id = $1
ORDER BY ordinal
`

type ListProfileVersionCapsuleRefsRow struct {
	Ordinal         int32
	Ref             string
	FreshnessPolicy string
	Exclusions      []byte
}

func (q *Queries) ListProfileVersionCapsuleRefs(ctx context.Context, profileVersionID string) ([]ListProfileVersionCapsuleRefsRow, error) {
	rows, err := q.db.Query(ctx, listProfileVersionCapsuleRefs, profileVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProfileVersionCapsuleRefsRow{}
	for rows.Next() {
		var i ListProfileVersionCapsuleRefsRow
		if err := rows.Scan(
			&i.Ordinal,
			&i.Ref,
			&i.FreshnessPolicy,
			&i.Exclusions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProfileCreateRegistration = `-- name: LockProfileCreateRegistration :one
SELECT pg_advisory_xact_lock(
    hashtextextended('profile-create' || chr(31) || $1::text || chr(31) || $2::text, 0)
)
`

type LockProfileCreateRegistrationParams struct {
	OwnerUserID    string
	IdempotencyKey string
}

func (q *Queries) LockProfileCreateRegistration(ctx context.Context, arg LockProfileCreateRegistrationParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, lockProfileCreateRegistration, arg.OwnerUserID, arg.IdempotencyKey)
	var pg_advisory_xact_lock interface{}
	err := row.Scan(&pg_advisory_xact_lock)
	return pg_advisory_xact_lock, err
}

const lockProfilePublicationRegistration = `-- name: LockProfilePublicationRegistration :one
SELECT pg_advisory_xact_lock(
    hashtextextended('profile-publication' || chr(31) || $1::text || chr(31) || $2::text, 0)
)
`

type LockProfilePublicationRegistrationParams struct {
	OwnerUserID    string
	IdempotencyKey string
}

func (q *Queries) LockProfilePublicationRegistration(ctx context.Context, arg LockProfilePublicationRegistrationParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, lockProfilePublicationRegistration, arg.OwnerUserID, arg.IdempotencyKey)
	var pg_advisory_xact_lock interface{}
	err := row.Scan(&pg_advisory_xact_lock)
	return pg_advisory_xact_lock, err
}
