// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_seeds.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEnvironmentProjectSeed = `-- name: GetEnvironmentProjectSeed :one
SELECT
    id,
    owner_user_id,
    repository_url,
    base_revision,
    digest,
    git_bundle_digest,
    tracked_patch_digest,
    untracked_bundle_digest,
    manifest_digest,
    created_at
FROM project_seeds
WHERE id = $1
  AND owner_user_id = $2
  AND environment_id = $3
`

type GetEnvironmentProjectSeedParams struct {
	ID            string
	OwnerUserID   string
	EnvironmentID *string
}

type GetEnvironmentProjectSeedRow struct {
	ID                    string
	OwnerUserID           string
	RepositoryUrl         string
	BaseRevision          string
	Digest                string
	GitBundleDigest       *string
	TrackedPatchDigest    *string
	UntrackedBundleDigest *string
	ManifestDigest        string
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) GetEnvironmentProjectSeed(ctx context.Context, arg GetEnvironmentProjectSeedParams) (GetEnvironmentProjectSeedRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentProjectSeed, arg.ID, arg.OwnerUserID, arg.EnvironmentID)
	var i GetEnvironmentProjectSeedRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.RepositoryUrl,
		&i.BaseRevision,
		&i.Digest,
		&i.GitBundleDigest,
		&i.TrackedPatchDigest,
		&i.UntrackedBundleDigest,
		&i.ManifestDigest,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectSeedByDigest = `-- name: GetProjectSeedByDigest :one
SELECT
    id,
    owner_user_id,
    repository_url,
    base_revision,
    digest,
    git_bundle_digest,
    tracked_patch_digest,
    untracked_bundle_digest,
    manifest_digest,
    created_at
FROM project_seeds
WHERE owner_user_id = $1
  AND digest = $2
`

type GetProjectSeedByDigestParams struct {
	OwnerUserID string
	Digest      string
}

type GetProjectSeedByDigestRow struct {
	ID                    string
	OwnerUserID           string
	RepositoryUrl         string
	BaseRevision          string
	Digest                string
	GitBundleDigest       *string
	TrackedPatchDigest    *string
	UntrackedBundleDigest *string
	ManifestDigest        string
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) GetProjectSeedByDigest(ctx context.Context, arg GetProjectSeedByDigestParams) (GetProjectSeedByDigestRow, error) {
	row := q.db.QueryRow(ctx, getProjectSeedByDigest, arg.OwnerUserID, arg.Digest)
	var i GetProjectSeedByDigestRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.RepositoryUrl,
		&i.BaseRevision,
		&i.Digest,
		&i.GitBundleDigest,
		&i.TrackedPatchDigest,
		&i.UntrackedBundleDigest,
		&i.ManifestDigest,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectSeedRegistration = `-- name: GetProjectSeedRegistration :one
SELECT
    ps.id,
    ps.owner_user_id,
    ps.repository_url,
    ps.base_revision,
    ps.digest,
    ps.git_bundle_digest,
    ps.tracked_patch_digest,
    ps.untracked_bundle_digest,
    ps.manifest_digest,
    ps.created_at,
    registration.input
FROM project_seed_registrations registration
JOIN project_seeds ps ON ps.id = registration.project_seed_id
WHERE registration.owner_user_id = $1
  AND registration.idempotency_key = $2
`

type GetProjectSeedRegistrationParams struct {
	OwnerUserID    string
	IdempotencyKey string
}

type GetProjectSeedRegistrationRow struct {
	ID                    string
	OwnerUserID           string
	RepositoryUrl         string
	BaseRevision          string
	Digest                string
	GitBundleDigest       *string
	TrackedPatchDigest    *string
	UntrackedBundleDigest *string
	ManifestDigest        string
	CreatedAt             pgtype.Timestamptz
	Input                 []byte
}

func (q *Queries) GetProjectSeedRegistration(ctx context.Context, arg GetProjectSeedRegistrationParams) (GetProjectSeedRegistrationRow, error) {
	row := q.db.QueryRow(ctx, getProjectSeedRegistration, arg.OwnerUserID, arg.IdempotencyKey)
	var i GetProjectSeedRegistrationRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.RepositoryUrl,
		&i.BaseRevision,
		&i.Digest,
		&i.GitBundleDigest,
		&i.TrackedPatchDigest,
		&i.UntrackedBundleDigest,
		&i.ManifestDigest,
		&i.CreatedAt,
		&i.Input,
	)
	return i, err
}

const insertProjectSeed = `-- name: InsertProjectSeed :one
INSERT INTO project_seeds (
    id,
    owner_user_id,
    repository_url,
    base_revision,
    digest,
    git_bundle_digest,
    tracked_patch_digest,
    untracked_bundle_digest,
    manifest_digest,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING
    id,
    owner_user_id,
    repository_url,
    base_revision,
    digest,
    git_bundle_digest,
    tracked_patch_digest,
    untracked_bundle_digest,
    manifest_digest,
    created_at
`

type InsertProjectSeedParams struct {
	ID                    string
	OwnerUserID           string
	RepositoryUrl         string
	BaseRevision          string
	Digest                string
	GitBundleDigest       *string
	TrackedPatchDigest    *string
	UntrackedBundleDigest *string
	ManifestDigest        string
	CreatedAt             pgtype.Timestamptz
}

type InsertProjectSeedRow struct {
	ID                    string
	OwnerUserID           string
	RepositoryUrl         string
	BaseRevision          string
	Digest                string
	GitBundleDigest       *string
	TrackedPatchDigest    *string
	UntrackedBundleDigest *string
	ManifestDigest        string
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) InsertProjectSeed(ctx context.Context, arg InsertProjectSeedParams) (InsertProjectSeedRow, error) {
	row := q.db.QueryRow(ctx, insertProjectSeed,
		arg.ID,
		arg.OwnerUserID,
		arg.RepositoryUrl,
		arg.BaseRevision,
		arg.Digest,
		arg.GitBundleDigest,
		arg.TrackedPatchDigest,
		arg.UntrackedBundleDigest,
		arg.ManifestDigest,
		arg.CreatedAt,
	)
	var i InsertProjectSeedRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.RepositoryUrl,
		&i.BaseRevision,
		&i.Digest,
		&i.GitBundleDigest,
		&i.TrackedPatchDigest,
		&i.UntrackedBundleDigest,
		&i.ManifestDigest,
		&i.CreatedAt,
	)
	return i, err
}

const insertProjectSeedRegistration = `-- name: InsertProjectSeedRegistration :exec
INSERT INTO project_seed_registrations (
    owner_user_id,
    idempotency_key,
    input,
    project_seed_id
) VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type InsertProjectSeedRegistrationParams struct {
	OwnerUserID    string
	IdempotencyKey string
	Input          []byte
	ProjectSeedID  string
}

func (q *Queries) InsertProjectSeedRegistration(ctx context.Context, arg InsertProjectSeedRegistrationParams) error {
	_, err := q.db.Exec(ctx, insertProjectSeedRegistration,
		arg.OwnerUserID,
		arg.IdempotencyKey,
		arg.Input,
		arg.ProjectSeedID,
	)
	return err
}

const lockProjectSeedDigest = `-- name: LockProjectSeedDigest :one
SELECT pg_advisory_xact_lock(
    hashtextextended('project-seed-digest' || chr(31) || $1::text || chr(31) || $2::text, 0)
)
`

type LockProjectSeedDigestParams struct {
	OwnerUserID string
	Digest      string
}

func (q *Queries) LockProjectSeedDigest(ctx context.Context, arg LockProjectSeedDigestParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, lockProjectSeedDigest, arg.OwnerUserID, arg.Digest)
	var pg_advisory_xact_lock interface{}
	err := row.Scan(&pg_advisory_xact_lock)
	return pg_advisory_xact_lock, err
}

const lockProjectSeedRegistration = `-- name: LockProjectSeedRegistration :one
SELECT pg_advisory_xact_lock(
    hashtextextended('project-seed' || chr(31) || $1::text || chr(31) || $2::text, 0)
)
`

type LockProjectSeedRegistrationParams struct {
	OwnerUserID    string
	IdempotencyKey string
}

func (q *Queries) LockProjectSeedRegistration(ctx context.Context, arg LockProjectSeedRegistrationParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, lockProjectSeedRegistration, arg.OwnerUserID, arg.IdempotencyKey)
	var pg_advisory_xact_lock interface{}
	err := row.Scan(&pg_advisory_xact_lock)
	return pg_advisory_xact_lock, err
}
