// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_resource_retention.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const pruneProviderResources = `-- name: PruneProviderResources :execrows
WITH candidates AS MATERIALIZED (
    SELECT resource.id
    FROM provider_resources resource
    WHERE resource.deleted_at < $1
      AND NOT EXISTS (
          SELECT 1
          FROM environments environment
          WHERE environment.id = resource.environment_id
            AND environment.current_runtime_id = resource.runtime_id
      )
      AND NOT EXISTS (
          SELECT 1
          FROM state_components component
          WHERE component.environment_id = resource.environment_id
            AND component.backend_resource_id = resource.id
      )
), cleared_runtime_references AS (
    UPDATE runtimes
    SET provider_resource_id = NULL
    WHERE provider_resource_id IN (SELECT id FROM candidates)
    RETURNING id
)
DELETE FROM provider_resources resource
USING candidates
WHERE resource.id = candidates.id
`

func (q *Queries) PruneProviderResources(ctx context.Context, retainAfter pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, pruneProviderResources, retainAfter)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
