// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime_operations.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOperationByIdempotencyKey = `-- name: GetOperationByIdempotencyKey :one
SELECT id, environment_id, type, status, requested_by_user_id, idempotency_key,
       restate_invocation_id, input, created_at, completed_at
FROM operations
WHERE requested_by_user_id = $1
  AND idempotency_key = $2
`

type GetOperationByIdempotencyKeyParams struct {
	OwnerUserID    string
	IdempotencyKey string
}

type GetOperationByIdempotencyKeyRow struct {
	ID                  string
	EnvironmentID       string
	Type                string
	Status              string
	RequestedByUserID   string
	IdempotencyKey      string
	RestateInvocationID *string
	Input               []byte
	CreatedAt           pgtype.Timestamptz
	CompletedAt         pgtype.Timestamptz
}

func (q *Queries) GetOperationByIdempotencyKey(ctx context.Context, arg GetOperationByIdempotencyKeyParams) (GetOperationByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getOperationByIdempotencyKey, arg.OwnerUserID, arg.IdempotencyKey)
	var i GetOperationByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Type,
		&i.Status,
		&i.RequestedByUserID,
		&i.IdempotencyKey,
		&i.RestateInvocationID,
		&i.Input,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getOwnedRuntimeStateForUpdate = `-- name: GetOwnedRuntimeStateForUpdate :one
SELECT
    e.id AS environment_id,
    e.owner_user_id,
    e.name,
    e.slug,
    e.lifecycle,
    e.health,
    e.region AS environment_region,
    e.availability_zone AS environment_availability_zone,
    e.runtime_preset AS environment_runtime_preset,
    e.pinned_profile_version_id,
    e.current_runtime_id,
    p.id AS auto_stop_policy_id,
    e.created_at AS environment_created_at,
    e.updated_at AS environment_updated_at,
    e.deleted_at,
    e.version AS environment_version,
    r.id AS runtime_id,
    r.environment_id AS runtime_environment_id,
    r.sequence,
    r.status AS runtime_status,
    r.runtime_preset AS runtime_runtime_preset,
    r.region AS runtime_region,
    r.availability_zone AS runtime_availability_zone,
    r.image_version,
    r.provider_instance_ref,
    r.private_address,
    r.boot_id,
    r.started_at,
    r.stopped_at,
    r.retired_at,
    r.created_at AS runtime_created_at,
    r.updated_at AS runtime_updated_at,
    r.version AS runtime_version
FROM environments e
JOIN auto_stop_policies p ON p.environment_id = e.id
JOIN runtimes r
  ON r.environment_id = e.id
 AND r.id = COALESCE($1, e.current_runtime_id)
WHERE e.id = $2
  AND e.owner_user_id = $3
FOR UPDATE OF e, r
`

type GetOwnedRuntimeStateForUpdateParams struct {
	RuntimeID     *string
	EnvironmentID string
	OwnerUserID   string
}

type GetOwnedRuntimeStateForUpdateRow struct {
	EnvironmentID               string
	OwnerUserID                 string
	Name                        string
	Slug                        string
	Lifecycle                   string
	Health                      string
	EnvironmentRegion           string
	EnvironmentAvailabilityZone string
	EnvironmentRuntimePreset    string
	PinnedProfileVersionID      string
	CurrentRuntimeID            *string
	AutoStopPolicyID            string
	EnvironmentCreatedAt        pgtype.Timestamptz
	EnvironmentUpdatedAt        pgtype.Timestamptz
	DeletedAt                   pgtype.Timestamptz
	EnvironmentVersion          int64
	RuntimeID                   string
	RuntimeEnvironmentID        string
	Sequence                    int64
	RuntimeStatus               string
	RuntimeRuntimePreset        string
	RuntimeRegion               string
	RuntimeAvailabilityZone     string
	ImageVersion                string
	ProviderInstanceRef         *string
	PrivateAddress              *string
	BootID                      *string
	StartedAt                   pgtype.Timestamptz
	StoppedAt                   pgtype.Timestamptz
	RetiredAt                   pgtype.Timestamptz
	RuntimeCreatedAt            pgtype.Timestamptz
	RuntimeUpdatedAt            pgtype.Timestamptz
	RuntimeVersion              int64
}

func (q *Queries) GetOwnedRuntimeStateForUpdate(ctx context.Context, arg GetOwnedRuntimeStateForUpdateParams) (GetOwnedRuntimeStateForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getOwnedRuntimeStateForUpdate, arg.RuntimeID, arg.EnvironmentID, arg.OwnerUserID)
	var i GetOwnedRuntimeStateForUpdateRow
	err := row.Scan(
		&i.EnvironmentID,
		&i.OwnerUserID,
		&i.Name,
		&i.Slug,
		&i.Lifecycle,
		&i.Health,
		&i.EnvironmentRegion,
		&i.EnvironmentAvailabilityZone,
		&i.EnvironmentRuntimePreset,
		&i.PinnedProfileVersionID,
		&i.CurrentRuntimeID,
		&i.AutoStopPolicyID,
		&i.EnvironmentCreatedAt,
		&i.EnvironmentUpdatedAt,
		&i.DeletedAt,
		&i.EnvironmentVersion,
		&i.RuntimeID,
		&i.RuntimeEnvironmentID,
		&i.Sequence,
		&i.RuntimeStatus,
		&i.RuntimeRuntimePreset,
		&i.RuntimeRegion,
		&i.RuntimeAvailabilityZone,
		&i.ImageVersion,
		&i.ProviderInstanceRef,
		&i.PrivateAddress,
		&i.BootID,
		&i.StartedAt,
		&i.StoppedAt,
		&i.RetiredAt,
		&i.RuntimeCreatedAt,
		&i.RuntimeUpdatedAt,
		&i.RuntimeVersion,
	)
	return i, err
}

const getPendingRuntimeOperation = `-- name: GetPendingRuntimeOperation :one
SELECT outbox.operation_id, target.operation_type, target.environment_id, target.runtime_id
FROM workflow_outbox outbox
JOIN runtime_operation_targets target
  ON target.operation_id = outbox.operation_id
 AND target.operation_type = outbox.kind
WHERE outbox.operation_id = $1
  AND outbox.started_at IS NULL
  AND outbox.kind IN ('runtime.start', 'runtime.stop', 'runtime.replace')
`

type GetPendingRuntimeOperationRow struct {
	OperationID   string
	OperationType string
	EnvironmentID string
	RuntimeID     string
}

func (q *Queries) GetPendingRuntimeOperation(ctx context.Context, operationID string) (GetPendingRuntimeOperationRow, error) {
	row := q.db.QueryRow(ctx, getPendingRuntimeOperation, operationID)
	var i GetPendingRuntimeOperationRow
	err := row.Scan(
		&i.OperationID,
		&i.OperationType,
		&i.EnvironmentID,
		&i.RuntimeID,
	)
	return i, err
}

const getRuntimeOperationTarget = `-- name: GetRuntimeOperationTarget :one
SELECT runtime_id
FROM runtime_operation_targets
WHERE operation_id = $1
`

func (q *Queries) GetRuntimeOperationTarget(ctx context.Context, operationID string) (string, error) {
	row := q.db.QueryRow(ctx, getRuntimeOperationTarget, operationID)
	var runtime_id string
	err := row.Scan(&runtime_id)
	return runtime_id, err
}

const insertRuntimeOperation = `-- name: InsertRuntimeOperation :exec
INSERT INTO operations (
    id, environment_id, type, status, requested_by_user_id, idempotency_key, input, created_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
`

type InsertRuntimeOperationParams struct {
	ID                string
	EnvironmentID     string
	Type              string
	Status            string
	RequestedByUserID string
	IdempotencyKey    string
	Input             []byte
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) InsertRuntimeOperation(ctx context.Context, arg InsertRuntimeOperationParams) error {
	_, err := q.db.Exec(ctx, insertRuntimeOperation,
		arg.ID,
		arg.EnvironmentID,
		arg.Type,
		arg.Status,
		arg.RequestedByUserID,
		arg.IdempotencyKey,
		arg.Input,
		arg.CreatedAt,
	)
	return err
}

const insertRuntimeOperationOutbox = `-- name: InsertRuntimeOperationOutbox :exec
INSERT INTO workflow_outbox (operation_id, kind, created_at)
VALUES ($1, $2, $3)
`

type InsertRuntimeOperationOutboxParams struct {
	OperationID string
	Kind        string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertRuntimeOperationOutbox(ctx context.Context, arg InsertRuntimeOperationOutboxParams) error {
	_, err := q.db.Exec(ctx, insertRuntimeOperationOutbox, arg.OperationID, arg.Kind, arg.CreatedAt)
	return err
}

const insertRuntimeOperationTarget = `-- name: InsertRuntimeOperationTarget :exec
INSERT INTO runtime_operation_targets (operation_id, environment_id, runtime_id, operation_type)
VALUES ($1, $2, $3, $4)
`

type InsertRuntimeOperationTargetParams struct {
	OperationID   string
	EnvironmentID string
	RuntimeID     string
	OperationType string
}

func (q *Queries) InsertRuntimeOperationTarget(ctx context.Context, arg InsertRuntimeOperationTargetParams) error {
	_, err := q.db.Exec(ctx, insertRuntimeOperationTarget,
		arg.OperationID,
		arg.EnvironmentID,
		arg.RuntimeID,
		arg.OperationType,
	)
	return err
}

const listPendingRuntimeOperations = `-- name: ListPendingRuntimeOperations :many
SELECT outbox.operation_id, target.operation_type, target.environment_id, target.runtime_id
FROM workflow_outbox outbox
JOIN runtime_operation_targets target
  ON target.operation_id = outbox.operation_id
 AND target.operation_type = outbox.kind
WHERE outbox.started_at IS NULL
  AND outbox.kind IN ('runtime.start', 'runtime.stop', 'runtime.replace')
ORDER BY outbox.created_at, outbox.operation_id
LIMIT $1
`

type ListPendingRuntimeOperationsRow struct {
	OperationID   string
	OperationType string
	EnvironmentID string
	RuntimeID     string
}

func (q *Queries) ListPendingRuntimeOperations(ctx context.Context, limitCount int32) ([]ListPendingRuntimeOperationsRow, error) {
	rows, err := q.db.Query(ctx, listPendingRuntimeOperations, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingRuntimeOperationsRow{}
	for rows.Next() {
		var i ListPendingRuntimeOperationsRow
		if err := rows.Scan(
			&i.OperationID,
			&i.OperationType,
			&i.EnvironmentID,
			&i.RuntimeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRuntimeOperationIdempotency = `-- name: LockRuntimeOperationIdempotency :one
SELECT pg_advisory_xact_lock(
    hashtextextended('runtime-operation' || chr(31) || $1::text || chr(31) || $2::text, 0)
)
`

type LockRuntimeOperationIdempotencyParams struct {
	OwnerUserID    string
	IdempotencyKey string
}

func (q *Queries) LockRuntimeOperationIdempotency(ctx context.Context, arg LockRuntimeOperationIdempotencyParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, lockRuntimeOperationIdempotency, arg.OwnerUserID, arg.IdempotencyKey)
	var pg_advisory_xact_lock interface{}
	err := row.Scan(&pg_advisory_xact_lock)
	return pg_advisory_xact_lock, err
}
