// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime_creation.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachInitialRuntime = `-- name: AttachInitialRuntime :execrows
UPDATE environments
SET current_runtime_id = $1,
    updated_at = $2,
    version = $3
WHERE id = $4
  AND current_runtime_id IS NULL
  AND version = $5
`

type AttachInitialRuntimeParams struct {
	RuntimeID      *string
	UpdatedAt      pgtype.Timestamptz
	NextVersion    int64
	EnvironmentID  string
	CurrentVersion int64
}

func (q *Queries) AttachInitialRuntime(ctx context.Context, arg AttachInitialRuntimeParams) (int64, error) {
	result, err := q.db.Exec(ctx, attachInitialRuntime,
		arg.RuntimeID,
		arg.UpdatedAt,
		arg.NextVersion,
		arg.EnvironmentID,
		arg.CurrentVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInitialRuntimeForUpdate = `-- name: GetInitialRuntimeForUpdate :one
SELECT id, environment_id, sequence, status, runtime_preset, region, availability_zone,
       image_version, provider_instance_ref, private_address, boot_id, started_at,
       stopped_at, retired_at, created_at, updated_at, version
FROM runtimes
WHERE id = $1
  AND environment_id = $2
FOR UPDATE
`

type GetInitialRuntimeForUpdateParams struct {
	RuntimeID     string
	EnvironmentID string
}

type GetInitialRuntimeForUpdateRow struct {
	ID                  string
	EnvironmentID       string
	Sequence            int64
	Status              string
	RuntimePreset       string
	Region              string
	AvailabilityZone    string
	ImageVersion        string
	ProviderInstanceRef *string
	PrivateAddress      *string
	BootID              *string
	StartedAt           pgtype.Timestamptz
	StoppedAt           pgtype.Timestamptz
	RetiredAt           pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Version             int64
}

func (q *Queries) GetInitialRuntimeForUpdate(ctx context.Context, arg GetInitialRuntimeForUpdateParams) (GetInitialRuntimeForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getInitialRuntimeForUpdate, arg.RuntimeID, arg.EnvironmentID)
	var i GetInitialRuntimeForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Sequence,
		&i.Status,
		&i.RuntimePreset,
		&i.Region,
		&i.AvailabilityZone,
		&i.ImageVersion,
		&i.ProviderInstanceRef,
		&i.PrivateAddress,
		&i.BootID,
		&i.StartedAt,
		&i.StoppedAt,
		&i.RetiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertInitialRuntime = `-- name: InsertInitialRuntime :exec
INSERT INTO runtimes (
    id, environment_id, sequence, status, runtime_preset, region, availability_zone,
    image_version, provider_instance_ref, private_address, boot_id, started_at,
    stopped_at, retired_at, created_at, updated_at, version
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13, $14,
    $15, $16, $17
)
`

type InsertInitialRuntimeParams struct {
	ID                  string
	EnvironmentID       string
	Sequence            int64
	Status              string
	RuntimePreset       string
	Region              string
	AvailabilityZone    string
	ImageVersion        string
	ProviderInstanceRef *string
	PrivateAddress      *string
	BootID              *string
	StartedAt           pgtype.Timestamptz
	StoppedAt           pgtype.Timestamptz
	RetiredAt           pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Version             int64
}

func (q *Queries) InsertInitialRuntime(ctx context.Context, arg InsertInitialRuntimeParams) error {
	_, err := q.db.Exec(ctx, insertInitialRuntime,
		arg.ID,
		arg.EnvironmentID,
		arg.Sequence,
		arg.Status,
		arg.RuntimePreset,
		arg.Region,
		arg.AvailabilityZone,
		arg.ImageVersion,
		arg.ProviderInstanceRef,
		arg.PrivateAddress,
		arg.BootID,
		arg.StartedAt,
		arg.StoppedAt,
		arg.RetiredAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Version,
	)
	return err
}
