// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ssh_keys.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOwnedSSHKeyByFingerprint = `-- name: GetOwnedSSHKeyByFingerprint :one
SELECT id, owner_user_id, label, algorithm, fingerprint, public_key, created_at, revoked_at
FROM ssh_keys
WHERE owner_user_id = $1
  AND fingerprint = $2
`

type GetOwnedSSHKeyByFingerprintParams struct {
	OwnerUserID string
	Fingerprint string
}

func (q *Queries) GetOwnedSSHKeyByFingerprint(ctx context.Context, arg GetOwnedSSHKeyByFingerprintParams) (SshKey, error) {
	row := q.db.QueryRow(ctx, getOwnedSSHKeyByFingerprint, arg.OwnerUserID, arg.Fingerprint)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Label,
		&i.Algorithm,
		&i.Fingerprint,
		&i.PublicKey,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getOwnedSSHKeyForUpdate = `-- name: GetOwnedSSHKeyForUpdate :one
SELECT id, owner_user_id, label, algorithm, fingerprint, public_key, created_at, revoked_at
FROM ssh_keys
WHERE owner_user_id = $1
  AND id = $2
FOR UPDATE
`

type GetOwnedSSHKeyForUpdateParams struct {
	OwnerUserID string
	ID          string
}

func (q *Queries) GetOwnedSSHKeyForUpdate(ctx context.Context, arg GetOwnedSSHKeyForUpdateParams) (SshKey, error) {
	row := q.db.QueryRow(ctx, getOwnedSSHKeyForUpdate, arg.OwnerUserID, arg.ID)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Label,
		&i.Algorithm,
		&i.Fingerprint,
		&i.PublicKey,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSSHKeyRegistration = `-- name: GetSSHKeyRegistration :one
SELECT key.id, key.owner_user_id, key.label, key.algorithm, key.fingerprint,
       key.public_key, key.created_at, key.revoked_at, registration.input
FROM ssh_key_registrations registration
JOIN ssh_keys key ON key.id = registration.ssh_key_id
                 AND key.owner_user_id = registration.owner_user_id
WHERE registration.owner_user_id = $1
  AND registration.idempotency_key = $2
`

type GetSSHKeyRegistrationParams struct {
	OwnerUserID    string
	IdempotencyKey string
}

type GetSSHKeyRegistrationRow struct {
	ID          string
	OwnerUserID string
	Label       string
	Algorithm   string
	Fingerprint string
	PublicKey   string
	CreatedAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
	Input       []byte
}

func (q *Queries) GetSSHKeyRegistration(ctx context.Context, arg GetSSHKeyRegistrationParams) (GetSSHKeyRegistrationRow, error) {
	row := q.db.QueryRow(ctx, getSSHKeyRegistration, arg.OwnerUserID, arg.IdempotencyKey)
	var i GetSSHKeyRegistrationRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Label,
		&i.Algorithm,
		&i.Fingerprint,
		&i.PublicKey,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.Input,
	)
	return i, err
}

const insertSSHKey = `-- name: InsertSSHKey :exec
INSERT INTO ssh_keys (
    id, owner_user_id, label, algorithm, fingerprint, public_key, created_at, revoked_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
`

type InsertSSHKeyParams struct {
	ID          string
	OwnerUserID string
	Label       string
	Algorithm   string
	Fingerprint string
	PublicKey   string
	CreatedAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

func (q *Queries) InsertSSHKey(ctx context.Context, arg InsertSSHKeyParams) error {
	_, err := q.db.Exec(ctx, insertSSHKey,
		arg.ID,
		arg.OwnerUserID,
		arg.Label,
		arg.Algorithm,
		arg.Fingerprint,
		arg.PublicKey,
		arg.CreatedAt,
		arg.RevokedAt,
	)
	return err
}

const insertSSHKeyRegistration = `-- name: InsertSSHKeyRegistration :exec
INSERT INTO ssh_key_registrations (owner_user_id, idempotency_key, input, ssh_key_id)
VALUES ($1, $2, $3, $4)
`

type InsertSSHKeyRegistrationParams struct {
	OwnerUserID    string
	IdempotencyKey string
	Input          []byte
	SshKeyID       string
}

func (q *Queries) InsertSSHKeyRegistration(ctx context.Context, arg InsertSSHKeyRegistrationParams) error {
	_, err := q.db.Exec(ctx, insertSSHKeyRegistration,
		arg.OwnerUserID,
		arg.IdempotencyKey,
		arg.Input,
		arg.SshKeyID,
	)
	return err
}

const listActiveOwnedSSHKeys = `-- name: ListActiveOwnedSSHKeys :many
SELECT id, owner_user_id, label, algorithm, fingerprint, public_key, created_at, revoked_at
FROM ssh_keys
WHERE owner_user_id = $1
  AND revoked_at IS NULL
ORDER BY created_at, id
`

func (q *Queries) ListActiveOwnedSSHKeys(ctx context.Context, ownerUserID string) ([]SshKey, error) {
	rows, err := q.db.Query(ctx, listActiveOwnedSSHKeys, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SshKey{}
	for rows.Next() {
		var i SshKey
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Label,
			&i.Algorithm,
			&i.Fingerprint,
			&i.PublicKey,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSSHKeyFingerprint = `-- name: LockSSHKeyFingerprint :one
SELECT pg_advisory_xact_lock(
    hashtextextended('ssh-key-fingerprint' || chr(31) || $1::text || chr(31) || $2::text, 0)
)
`

type LockSSHKeyFingerprintParams struct {
	OwnerUserID string
	Fingerprint string
}

func (q *Queries) LockSSHKeyFingerprint(ctx context.Context, arg LockSSHKeyFingerprintParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, lockSSHKeyFingerprint, arg.OwnerUserID, arg.Fingerprint)
	var pg_advisory_xact_lock interface{}
	err := row.Scan(&pg_advisory_xact_lock)
	return pg_advisory_xact_lock, err
}

const lockSSHKeyRegistration = `-- name: LockSSHKeyRegistration :one
SELECT pg_advisory_xact_lock(
    hashtextextended('ssh-key' || chr(31) || $1::text || chr(31) || $2::text, 0)
)
`

type LockSSHKeyRegistrationParams struct {
	OwnerUserID    string
	IdempotencyKey string
}

func (q *Queries) LockSSHKeyRegistration(ctx context.Context, arg LockSSHKeyRegistrationParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, lockSSHKeyRegistration, arg.OwnerUserID, arg.IdempotencyKey)
	var pg_advisory_xact_lock interface{}
	err := row.Scan(&pg_advisory_xact_lock)
	return pg_advisory_xact_lock, err
}

const revokeOwnedSSHKey = `-- name: RevokeOwnedSSHKey :execrows
UPDATE ssh_keys
SET revoked_at = COALESCE(revoked_at, $1)
WHERE owner_user_id = $2
  AND id = $3
`

type RevokeOwnedSSHKeyParams struct {
	RevokedAt   pgtype.Timestamptz
	OwnerUserID string
	ID          string
}

func (q *Queries) RevokeOwnedSSHKey(ctx context.Context, arg RevokeOwnedSSHKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOwnedSSHKey, arg.RevokedAt, arg.OwnerUserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
