// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upload_intents.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOwnedUploadIntentByDigest = `-- name: GetOwnedUploadIntentByDigest :one
SELECT id, owner_user_id, kind, digest, size_bytes, object_key, created_at, expires_at
FROM upload_intents
WHERE owner_user_id = $1
  AND kind = $2
  AND digest = $3
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetOwnedUploadIntentByDigestParams struct {
	OwnerUserID string
	Kind        string
	Digest      string
}

func (q *Queries) GetOwnedUploadIntentByDigest(ctx context.Context, arg GetOwnedUploadIntentByDigestParams) (UploadIntent, error) {
	row := q.db.QueryRow(ctx, getOwnedUploadIntentByDigest, arg.OwnerUserID, arg.Kind, arg.Digest)
	var i UploadIntent
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Kind,
		&i.Digest,
		&i.SizeBytes,
		&i.ObjectKey,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUploadIntentRegistration = `-- name: GetUploadIntentRegistration :one
SELECT intent.id, intent.owner_user_id, intent.kind, intent.digest, intent.size_bytes,
       intent.object_key, intent.created_at, intent.expires_at, registration.input
FROM upload_intent_registrations registration
JOIN upload_intents intent ON intent.id = registration.upload_intent_id
                          AND intent.owner_user_id = registration.owner_user_id
WHERE registration.owner_user_id = $1
  AND registration.idempotency_key = $2
`

type GetUploadIntentRegistrationParams struct {
	OwnerUserID    string
	IdempotencyKey string
}

type GetUploadIntentRegistrationRow struct {
	ID          string
	OwnerUserID string
	Kind        string
	Digest      string
	SizeBytes   int64
	ObjectKey   string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	Input       []byte
}

func (q *Queries) GetUploadIntentRegistration(ctx context.Context, arg GetUploadIntentRegistrationParams) (GetUploadIntentRegistrationRow, error) {
	row := q.db.QueryRow(ctx, getUploadIntentRegistration, arg.OwnerUserID, arg.IdempotencyKey)
	var i GetUploadIntentRegistrationRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Kind,
		&i.Digest,
		&i.SizeBytes,
		&i.ObjectKey,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Input,
	)
	return i, err
}

const insertUploadIntent = `-- name: InsertUploadIntent :one
INSERT INTO upload_intents (
    id, owner_user_id, kind, digest, size_bytes, object_key, created_at, expires_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
RETURNING id, owner_user_id, kind, digest, size_bytes, object_key, created_at, expires_at
`

type InsertUploadIntentParams struct {
	ID          string
	OwnerUserID string
	Kind        string
	Digest      string
	SizeBytes   int64
	ObjectKey   string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) InsertUploadIntent(ctx context.Context, arg InsertUploadIntentParams) (UploadIntent, error) {
	row := q.db.QueryRow(ctx, insertUploadIntent,
		arg.ID,
		arg.OwnerUserID,
		arg.Kind,
		arg.Digest,
		arg.SizeBytes,
		arg.ObjectKey,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i UploadIntent
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Kind,
		&i.Digest,
		&i.SizeBytes,
		&i.ObjectKey,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertUploadIntentRegistration = `-- name: InsertUploadIntentRegistration :exec
INSERT INTO upload_intent_registrations (owner_user_id, idempotency_key, input, upload_intent_id)
VALUES ($1, $2, $3, $4)
`

type InsertUploadIntentRegistrationParams struct {
	OwnerUserID    string
	IdempotencyKey string
	Input          []byte
	UploadIntentID string
}

func (q *Queries) InsertUploadIntentRegistration(ctx context.Context, arg InsertUploadIntentRegistrationParams) error {
	_, err := q.db.Exec(ctx, insertUploadIntentRegistration,
		arg.OwnerUserID,
		arg.IdempotencyKey,
		arg.Input,
		arg.UploadIntentID,
	)
	return err
}

const lockUploadIntentRegistration = `-- name: LockUploadIntentRegistration :one
SELECT pg_advisory_xact_lock(
    hashtextextended('upload-intent' || chr(31) || $1::text || chr(31) || $2::text, 0)
)
`

type LockUploadIntentRegistrationParams struct {
	OwnerUserID    string
	IdempotencyKey string
}

func (q *Queries) LockUploadIntentRegistration(ctx context.Context, arg LockUploadIntentRegistrationParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, lockUploadIntentRegistration, arg.OwnerUserID, arg.IdempotencyKey)
	var pg_advisory_xact_lock interface{}
	err := row.Scan(&pg_advisory_xact_lock)
	return pg_advisory_xact_lock, err
}
