// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureUser = `-- name: EnsureUser :one
INSERT INTO users (
    id,
    workos_user_id,
    default_region,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $4
)
ON CONFLICT (workos_user_id) DO UPDATE
SET updated_at = GREATEST(users.updated_at, EXCLUDED.updated_at)
RETURNING id, workos_user_id, default_region, created_at, updated_at
`

type EnsureUserParams struct {
	ID            string
	WorkosUserID  string
	DefaultRegion string
	ObservedAt    pgtype.Timestamptz
}

func (q *Queries) EnsureUser(ctx context.Context, arg EnsureUserParams) (User, error) {
	row := q.db.QueryRow(ctx, ensureUser,
		arg.ID,
		arg.WorkosUserID,
		arg.DefaultRegion,
		arg.ObservedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WorkosUserID,
		&i.DefaultRegion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
